[
uuid(1d55b526-c137-46c5-ab79-638f2a68e869),
version(1.0),
]
interface DefaultIfName
{typedef struct Struct_2_t
{
short StructMember0;
short StructMember1;
}Struct_2_t;
typedef struct Struct_186_t
{
byte StructMember0;
byte StructMember1;
byte StructMember2;
short StructMember3;
[unique] [size_is(StructMember3)] /*[range(0,200)] */ char *StructMember4;
}Struct_186_t;
typedef struct Struct_304_t
{
byte StructMember0;
short StructMember1;
long StructMember2;
short StructMember3;
[unique] [size_is(StructMember3)] /*[range(0,300)] */ char *StructMember4;
}Struct_304_t;
typedef [switch_type(short )] union union_100
{
[case(0)] struct Struct_2_t unionMember_0;
[case(1)] struct Struct_2_t unionMember_1;
}union_100;
typedef struct Struct_144_t
{
byte StructMember0;
short StructMember1;
long StructMember2;
short StructMember3;
struct Struct_2_t StructMember4;
}Struct_144_t;
typedef struct Struct_228_t
{
byte StructMember0;
short StructMember1;
struct Struct_2_t StructMember2;
long StructMember3;
long StructMember4;
struct Struct_2_t StructMember5;
short StructMember6;
[unique] [size_is(StructMember6)] /*[range(0,200)] */ char *StructMember7;
}Struct_228_t;
typedef struct Struct_264_t
{
byte StructMember0;
byte StructMember1;
short StructMember2;
struct Struct_2_t StructMember3;
long StructMember4[2] ;
long StructMember5;
long StructMember6;
}Struct_264_t;
typedef struct Struct_118_t
{
byte StructMember0;
byte StructMember1;
short StructMember2;
long StructMember3;
struct Struct_2_t StructMember4;
long StructMember5;
long StructMember6;
long StructMember7;
 short StructMember8;
[switch_is(StructMember8)] union union_100 StructMember9;
}Struct_118_t;
typedef [switch_type(short )] union union_38
{
[case(2)] struct Struct_118_t unionMember_2;
[case(3)] struct Struct_144_t unionMember_3;
[case(4)] struct Struct_186_t unionMember_4;
[case(5)] struct Struct_228_t unionMember_5;
[case(6)] struct Struct_264_t unionMember_6;
[case(7)] struct Struct_304_t unionMember_7;
}union_38;
typedef struct Struct_324_t
{
short StructMember0;
[switch_is(StructMember0)] union union_38 StructMember1;
}Struct_324_t;
error_status_t Proc0_RemoteGetCellByDebugCellID(
[in]long arg_1,
[in]struct Struct_2_t arg_2,
[in][out][unique]struct Struct_324_t** arg_3);

error_status_t Proc1_RemoteOpenRPCDebugCallInfoEnumeration(
[out]/* simple_ref */[context_handle] void** arg_1,
[in]long arg_2,
[in]long arg_3,
[in]long arg_4,
[in]long arg_5);

error_status_t Proc2_RemoteGetNextRPCDebugCallInfo(
[in][context_handle] void* arg_0,
[in][out][unique]struct Struct_118_t** arg_1,
[out]/* simple_ref */struct Struct_2_t* arg_2,
[out]/* simple_ref */long *arg_3);

error_status_t Proc3_RemoteFinishRPCDebugCallInfoEnumeration(
[in][out]/* simple_ref */[context_handle] void** arg_0);

error_status_t Proc4_RemoteOpenRPCDebugEndpointInfoEnumeration(
[out]/* simple_ref */[context_handle] void** arg_1,
[in][range(0,200)] short arg_2,
[in][unique][size_is(arg_2)]/*[range(0,200)]*/ char *arg_3);

error_status_t Proc5_RemoteGetNextRPCDebugEndpointInfo(
[in][context_handle] void* arg_0,
[in][out][unique]struct Struct_186_t** arg_1,
[out]/* simple_ref */struct Struct_2_t* arg_2,
[out]/* simple_ref */long *arg_3);

error_status_t Proc6_RemoteFinishRPCDebugEndpointInfoEnumeration(
[in][out]/* simple_ref */[context_handle] void** arg_0);

error_status_t Proc7_RemoteOpenRPCDebugThreadInfoEnumeration(
[out]/* simple_ref */[context_handle] void** arg_1,
[in]long arg_2,
[in]long arg_3);

error_status_t Proc8_RemoteGetNextRPCDebugThreadInfo(
[in][context_handle] void* arg_0,
[in][out][unique]struct Struct_144_t** arg_1,
[out]/* simple_ref */struct Struct_2_t* arg_2,
[out]/* simple_ref */long *arg_3);

error_status_t Proc9_RemoteFinishRPCDebugThreadInfoEnumeration(
[in][out]/* simple_ref */[context_handle] void** arg_0);

error_status_t Proc10_RemoteOpenRPCDebugClientCallInfoEnumeration(
[out]/* simple_ref */[context_handle] void** arg_1,
[in]long arg_2,
[in]long arg_3,
[in]long arg_4,
[in]long arg_5);

error_status_t Proc11_RemoteGetNextRPCDebugClientCallInfo(
[in][context_handle] void* arg_0,
[in][out][unique]struct Struct_228_t** arg_1,
[in][out][unique]struct Struct_304_t** arg_2,
[out]/* simple_ref */struct Struct_2_t* arg_3,
[out]/* simple_ref */long *arg_4);

error_status_t Proc12_RemoteFinishRPCDebugClientCallInfoEnumeration(
[in][out]/* simple_ref */[context_handle] void** arg_0);
}

