[
uuid(a500d4c6-0dd1-4543-bc0c-d5f93486eaf8),
version(1.0),
]
interface DefaultIfName
{typedef struct Struct_72_t
{
short StructMember0;
short StructMember1;
short StructMember2;
short StructMember3;
short StructMember4;
short StructMember5;
short StructMember6;
short StructMember7;
}Struct_72_t;
typedef struct Struct_112_t
{
long StructMember0;
long StructMember1;
long StructMember2;
long StructMember3;
}Struct_112_t;
typedef struct Struct_174_t
{
long StructMember0;
short StructMember1;
short StructMember2;
byte StructMember3[8] ;
}Struct_174_t;
typedef struct Struct_258_t
{
long StructMember0[2] ;
}Struct_258_t;
typedef struct Struct_86_t
{
struct Struct_72_t StructMember0;
long StructMember1;
long StructMember2;
long StructMember3;
long StructMember4;
}Struct_86_t;
typedef struct Struct_100_t
{
struct Struct_72_t StructMember0;
long StructMember1;
long StructMember2;
long StructMember3;
}Struct_100_t;
typedef [switch_type(/* enum_16 */ short )] union union_30
{
[case(0)] struct Struct_86_t unionMember_0;
[case(1)] struct Struct_86_t unionMember_1;
[case(2)] struct Struct_100_t unionMember_2;
[case(3)] struct Struct_112_t unionMember_3;
[case(4)] struct Struct_86_t unionMember_4;
[case(5)] struct Struct_86_t unionMember_5;
}union_30;
typedef struct Struct_144_t
{
 short StructMember0;
[switch_is(StructMember0)] union union_30 StructMember1;
long StructMember2;
[unique] [size_is(StructMember2)] /*[range(0,1024)] */ char *StructMember3;
}Struct_144_t;
error_status_t Proc0__TbiCreateEvent(
[in][unique][string] wchar_t* arg_1,
[in]/* simple_ref */struct Struct_144_t* arg_2,
[out]/* simple_ref */struct Struct_174_t* arg_3);

error_status_t Proc1__TbiDeleteEvent(
[in][unique][string] wchar_t* arg_1,
[in]/* simple_ref */struct Struct_174_t* arg_2);

error_status_t Proc2_TbiEnumerateEvents(
[in][unique][string] wchar_t* arg_1,
[out]/* simple_ref */long *arg_2,
[out][ref] /* [DBG] FC_BOGUS_ARRAY */ [size_is(, *arg_2)]/*[range(0,0)]*/  /*  */ struct Struct_174_t** arg_3);

error_status_t Proc3__TbiQueryEventData(
[in][unique][string] wchar_t* arg_1,
[in]/* simple_ref */struct Struct_174_t* arg_2,
[out]/* simple_ref */struct Struct_144_t* arg_3);

error_status_t Proc4__TbiUpdateEvent(
[in][unique][string] wchar_t* arg_1,
[in]/* simple_ref */struct Struct_174_t* arg_2,
[in]/* simple_ref */struct Struct_144_t* arg_3);

error_status_t Proc5_TbiCreateCEvent(
[in]/* simple_ref */struct Struct_144_t* arg_1,
[out]/* simple_ref */struct Struct_258_t* arg_2,
[out]/* simple_ref */[context_handle] void** arg_3);

error_status_t Proc6_TbiDeleteCEvent(
[in]struct Struct_258_t arg_1,
[in][out]/* simple_ref */[context_handle] void** arg_2);

error_status_t Proc7_TbiEnumerateCEvents(
[out]/* simple_ref */long *arg_1,
[out][ref] /* [DBG] FC_BOGUS_ARRAY */ [size_is(, *arg_1)]/*[range(0,0)]*/  /*  */ struct Struct_258_t** arg_2);

error_status_t Proc8_TbiQueryCEventData(
[in]struct Struct_258_t arg_1,
[out]/* simple_ref */struct Struct_144_t* arg_2);

error_status_t Proc9_TbiUpdateCEvent(
[in]struct Struct_258_t arg_1,
[in]/* simple_ref */struct Struct_144_t* arg_2);
}

