[
uuid(f6beaff7-1e19-4fbb-9f8f-b89e2018337c),
version(1.0),
]
interface DefaultIfName
{typedef struct Struct_84_t
{
[unique] [string]  wchar_t* StructMember0;
long StructMember1;
}Struct_84_t;
typedef struct Struct_146_t
{
long StructMember0;
long StructMember1;
long StructMember2;
}Struct_146_t;
typedef struct Struct_586_t
{
long StructMember0;
short StructMember1;
short StructMember2;
byte StructMember3[8] ;
}Struct_586_t;
typedef struct Struct_620_t
{
long StructMember0;
[unique] [size_is(StructMember0)] /*[range(0,524288)] */ small *StructMember1;
}Struct_620_t;
typedef struct Struct_658_t
{
long StructMember0;
[unique] [size_is(StructMember0)] /*[range(0,524288)] */ long *StructMember1;
}Struct_658_t;
typedef struct Struct_696_t
{
long StructMember0;
[unique] [size_is(StructMember0)] /*[range(0,262144)] */ hyper *StructMember1;
}Struct_696_t;
typedef struct Struct_754_t
{
long StructMember0;
[unique]  /* [DBG]  FC_BOGUS_ARRAY */ [size_is(StructMember0)] /*[range(0,4096)] */  /*  */ [string]  wchar_t** StructMember1;
}Struct_754_t;
typedef struct Struct_812_t
{
long StructMember0;
[unique]  /* [DBG]  FC_BOGUS_ARRAY */ [size_is(StructMember0)] /*[range(0,131072)] */  /*  */ struct Struct_586_t* StructMember1;
}Struct_812_t;
typedef [switch_type(long )] union union_500
{
[case(0)] long unionMember_0;
[case(1)] small unionMember_1;
[case(2)] long unionMember_2;
[case(3)] hyper unionMember_3;
[case(4)] [unique] [string]  wchar_t* unionMember_4;
[case(5)] [unique] struct Struct_586_t* unionMember_5;
[case(6)] struct Struct_620_t unionMember_6;
[case(7)] struct Struct_658_t unionMember_7;
[case(8)] struct Struct_696_t unionMember_8;
[case(9)] struct Struct_754_t unionMember_9;
[case(10)] struct Struct_812_t unionMember_10;
}union_500;
typedef struct Struct_828_t
{
 long StructMember0;
long StructMember1;
[switch_is(StructMember0)] union union_500 StructMember2;
}Struct_828_t;
typedef struct Struct_886_t
{
long StructMember0;
[unique]  /* [DBG]  FC_BOGUS_ARRAY */ [size_is(StructMember0)] /*[range(0,256)] */  /*  */ struct Struct_828_t* StructMember1;
}Struct_886_t;
error_status_t Proc0__EvtRpcRegisterRemoteSubscription(
[in][unique][range(0,512)] [string] wchar_t* arg_1,
[in][ref][range(1,1048576)] [string] wchar_t* arg_2,
[in][unique][range(0,1048576)] [string] wchar_t* arg_3,
[in]long arg_4,
[out]/* simple_ref */[context_handle] void** arg_5,
[out]/* simple_ref */[context_handle] void** arg_6,
[out]/* simple_ref */long *arg_7,
[out][ref] /* [DBG] FC_BOGUS_ARRAY */ [size_is(, *arg_7)]/*[range(0,512)]*/  /*  */ struct Struct_84_t** arg_8,
[out]/* simple_ref */struct Struct_146_t* arg_9);

error_status_t Proc1__EvtRpcRemoteSubscriptionNextAsync(
[in][context_handle] void* arg_1,
[in]long arg_2,
[in]long arg_3,
[out]/* simple_ref */long *arg_4,
[out][ref][size_is(, *arg_4)]/*[range(0,1024)]*/ long **arg_5,
[out][ref][size_is(, *arg_4)]/*[range(0,1024)]*/ long **arg_6,
[out]/* simple_ref */long *arg_7,
[out][ref][size_is(, *arg_7)]/*[range(0,2097152)]*/ byte **arg_8);

error_status_t Proc2__EvtRpcRemoteSubscriptionNext(
[in][context_handle] void* arg_0,
[in]long arg_1,
[in]long arg_2,
[in]long arg_3,
[out]/* simple_ref */long *arg_4,
[out][ref][size_is(, *arg_4)]/*[range(0,1024)]*/ long **arg_5,
[out][ref][size_is(, *arg_4)]/*[range(0,1024)]*/ long **arg_6,
[out]/* simple_ref */long *arg_7,
[out][ref][size_is(, *arg_7)]/*[range(0,2097152)]*/ byte **arg_8);

error_status_t Proc3__EvtRpcRemoteSubscriptionWaitAsync(
[in][context_handle] void* arg_1);

error_status_t Proc4__EvtRpcRegisterControllableOperation(
[out]/* simple_ref */[context_handle] void** arg_1);

error_status_t Proc5__EvtRpcRegisterLogQuery(
[in][unique][range(0,32768)] [string] wchar_t* arg_1,
[in][ref][range(1,1048576)] [string] wchar_t* arg_2,
[in]long arg_3,
[out]/* simple_ref */[context_handle] void** arg_4,
[out]/* simple_ref */[context_handle] void** arg_5,
[out]/* simple_ref */long *arg_6,
[out][ref] /* [DBG] FC_BOGUS_ARRAY */ [size_is(, *arg_6)]/*[range(0,512)]*/  /*  */ struct Struct_84_t** arg_7,
[out]/* simple_ref */struct Struct_146_t* arg_8);

error_status_t Proc6_EvtRpcClearLog(
[in][context_handle] void* arg_0,
[in][ref][range(0,512)] [string] wchar_t* arg_1,
[in][unique][range(0,32768)] [string] wchar_t* arg_2,
[in]long arg_3,
[out]/* simple_ref */struct Struct_146_t* arg_4);

error_status_t Proc7__EvtRpcExportLog(
[in][context_handle] void* arg_0,
[in][unique][range(0,512)] [string] wchar_t* arg_1,
[in][ref][range(1,1048576)] [string] wchar_t* arg_2,
[in][ref][range(1,32768)] [string] wchar_t* arg_3,
[in]long arg_4,
[out]/* simple_ref */struct Struct_146_t* arg_5);

error_status_t Proc8_EvtRpcLocalizeExportLog(
[in][context_handle] void* arg_0,
[in][ref][range(1,32768)] [string] wchar_t* arg_1,
[in]long arg_2,
[in]long arg_3,
[out]/* simple_ref */struct Struct_146_t* arg_4);

error_status_t Proc9__EvtRpcMessageRender(
[in][context_handle] void* arg_0,
[in][range(1,256)] long arg_1,
[in]/* simple_ref */[size_is(arg_1)]/*[range(1,256)]*/ byte *arg_2,
[in]long arg_3,
[in]/* simple_ref */struct Struct_886_t* arg_4,
[in]long arg_5,
[in]long arg_6,
[out]/* simple_ref */long *arg_7,
[out]/* simple_ref */long *arg_8,
[out][ref][size_is(, *arg_7)]/*[range(0,2097152)]*/ byte **arg_9,
[out]/* simple_ref */struct Struct_146_t* arg_10);

error_status_t Proc10_EvtRpcMessageRenderDefault(
[in][range(1,256)] long arg_1,
[in]/* simple_ref */[size_is(arg_1)]/*[range(1,256)]*/ byte *arg_2,
[in]long arg_3,
[in]/* simple_ref */struct Struct_886_t* arg_4,
[in]long arg_5,
[in]long arg_6,
[out]/* simple_ref */long *arg_7,
[out]/* simple_ref */long *arg_8,
[out][ref][size_is(, *arg_7)]/*[range(0,2097152)]*/ byte **arg_9,
[out]/* simple_ref */struct Struct_146_t* arg_10);

error_status_t Proc11__EvtRpcQueryNext(
[in][context_handle] void* arg_0,
[in]long arg_1,
[in]long arg_2,
[in]long arg_3,
[out]/* simple_ref */long *arg_4,
[out][ref][size_is(, *arg_4)]/*[range(0,1024)]*/ long **arg_5,
[out][ref][size_is(, *arg_4)]/*[range(0,1024)]*/ long **arg_6,
[out]/* simple_ref */long *arg_7,
[out][ref][size_is(, *arg_7)]/*[range(0,2097152)]*/ byte **arg_8);

error_status_t Proc12__EvtRpcQuerySeek(
[in][context_handle] void* arg_0,
[in]hyper arg_1,
[in][unique][range(0,1048576)] [string] wchar_t* arg_2,
[in]long arg_3,
[in]long arg_4,
[out]/* simple_ref */struct Struct_146_t* arg_5);

error_status_t Proc13_EvtRpcClose(
[in][out]/* simple_ref */[context_handle] void** arg_0);

error_status_t Proc14__EvtRpcCancel(
[in][context_handle] void* arg_0);

error_status_t Proc15__EvtRpcAssertConfig(
[in][ref][range(1,512)] [string] wchar_t* arg_1,
[in]long arg_2);

error_status_t Proc16__EvtRpcRetractConfig(
[in][ref][range(1,512)] [string] wchar_t* arg_1,
[in]long arg_2);

error_status_t Proc17__EvtRpcOpenLogHandle(
[in][ref][range(1,32768)] [string] wchar_t* arg_1,
[in]long arg_2,
[out]/* simple_ref */[context_handle] void** arg_3,
[out]/* simple_ref */struct Struct_146_t* arg_4);

error_status_t Proc18__EvtRpcGetLogFileInfo(
[in][context_handle] void* arg_0,
[in]long arg_1,
[in][range(0,2097152)] long arg_2,
[out]/* simple_ref */[size_is(arg_2)]/*[range(0,2097152)]*/ byte *arg_3,
[out]/* simple_ref */long *arg_4);

error_status_t Proc19__EvtRpcGetChannelList(
[in]long arg_1,
[out]/* simple_ref */long *arg_2,
[out][ref] /* [DBG] FC_BOGUS_ARRAY */ [size_is(, *arg_2)]/*[range(0,8192)]*/  /*  */ [string] wchar_t*** arg_3);

error_status_t Proc20__EvtRpcGetChannelConfig(
[in][ref][range(1,512)] [string] wchar_t* arg_1,
[in]long arg_2,
[out]/* simple_ref */struct Struct_886_t* arg_3);

error_status_t Proc21__EvtRpcPutChannelConfig(
[in][ref][range(1,512)] [string] wchar_t* arg_1,
[in]long arg_2,
[in]/* simple_ref */struct Struct_886_t* arg_3,
[out]/* simple_ref */struct Struct_146_t* arg_4);

error_status_t Proc22__EvtRpcGetPublisherList(
[in]long arg_1,
[out]/* simple_ref */long *arg_2,
[out][ref] /* [DBG] FC_BOGUS_ARRAY */ [size_is(, *arg_2)]/*[range(0,8192)]*/  /*  */ [string] wchar_t*** arg_3);

error_status_t Proc23_EvtRpcGetPublisherListForChannel(
[in]/* simple_ref */[string] wchar_t* arg_1,
[in]long arg_2,
[out]/* simple_ref */long *arg_3,
[out][ref] /* [DBG] FC_BOGUS_ARRAY */ [size_is(, *arg_3)]/*[range(0,8192)]*/  /*  */ [string] wchar_t*** arg_4);

error_status_t Proc24__EvtRpcGetPublisherMetadata(
[in][unique][range(0,2048)] [string] wchar_t* arg_1,
[in][unique][range(0,32768)] [string] wchar_t* arg_2,
[in]long arg_3,
[in]long arg_4,
[out]/* simple_ref */struct Struct_886_t* arg_5,
[out]/* simple_ref */[context_handle] void** arg_6);

error_status_t Proc25__EvtRpcGetPublisherResourceMetadata(
[in][context_handle] void* arg_0,
[in]long arg_1,
[in]long arg_2,
[out]/* simple_ref */struct Struct_886_t* arg_3);

error_status_t Proc26_EvtRpcGetEventMetadataEnum(
[in][context_handle] void* arg_0,
[in]long arg_1,
[in][unique][range(0,1048576)] [string] wchar_t* arg_2,
[out]/* simple_ref */[context_handle] void** arg_3);

error_status_t Proc27_EvtRpcGetNextEventMetadata(
[in][context_handle] void* arg_0,
[in]long arg_1,
[in]long arg_2,
[out]/* simple_ref */long *arg_3,
[out][ref] /* [DBG] FC_BOGUS_ARRAY */ [size_is(, *arg_3)]/*[range(0,256)]*/  /*  */ struct Struct_886_t** arg_4);

error_status_t Proc28__EvtRpcGetClassicLogDisplayName(
[in][ref][range(1,512)] [string] wchar_t* arg_1,
[in]long arg_2,
[in]long arg_3,
[out][ref][string] wchar_t** arg_4);
}

