[
uuid(c2d15ccf-a416-46dc-ba58-4624ac7a9123),
version(1.0),
]
interface DefaultIfName
{typedef struct Struct_310_t
{
long StructMember0;
long StructMember1;
}Struct_310_t;
long Proc0_RpcRegisterCurrentSessionAsyncNotification(
[in]long arg_1,
[out]/* simple_ref */[context_handle] void** arg_2);

long Proc1_RpcWaitAsyncNotificationEx(
[in][context_handle] void* arg_1,
[out][ref] /* [DBG] FC_BOGUS_ARRAY */ [size_is(, *arg_3)] /*  */ struct Struct_310_t** arg_2,
[out]/* simple_ref */long *arg_3);

long Proc2_RpcUnRegisterAsyncNotificationEx(
[in][out]/* simple_ref */[context_handle] void** arg_0);
}

