[
uuid(12345778-1234-abcd-ef00-0123456789ab),
version(1.0),
]
interface DefaultIfName
{typedef struct Struct_44_t
{
short StructMember0;
short StructMember1;
[unique]  /* [DBG]  FC_CVARRAY */[size_is(StructMember1/2)] [length_is(StructMember0/2)] wchar_t *StructMember2/*[]  CONFORMANT_ARRAY*/;
}Struct_44_t;
typedef struct Struct_62_t
{
long StructMember0;
long StructMember1;
}Struct_62_t;
typedef struct Struct_160_t
{
[range(0,262144)]  long StructMember0;
[unique] [size_is(StructMember0)] char *StructMember1;
}Struct_160_t;
typedef struct Struct_234_t
{
short StructMember0;
short StructMember1;
[unique]  /* [DBG]  FC_CVARRAY */[size_is(StructMember1)] [length_is(StructMember0)] char *StructMember2/*[]  CONFORMANT_ARRAY*/;
}Struct_234_t;
typedef struct Struct_258_t
{
char StructMember0[6] ;
}Struct_258_t;
typedef struct Struct_306_t
{
char StructMember0;
char StructMember1;
short StructMember2;
[size_is(/* FC_EXPR */(StructMember2 - 4))] char StructMember3[] ;
}Struct_306_t;
typedef struct Struct_350_t
{
long StructMember0;
 short StructMember1;
char StructMember2;
char StructMember3;
}Struct_350_t;
typedef struct Struct_518_t
{
hyper StructMember0;
}Struct_518_t;
typedef struct Struct_570_t
{
char StructMember0;
[unique] [size_is(StructMember2)] long *StructMember1;
[range(0,1000)]  long StructMember2;
}Struct_570_t;
typedef struct Struct_642_t
{
 short StructMember0;
}Struct_642_t;
typedef struct Struct_716_t
{
char StructMember0;
}Struct_716_t;
typedef struct Struct_722_t
{
char StructMember0;
char StructMember1;
}Struct_722_t;
typedef struct Struct_736_t
{
long StructMember0;
short StructMember1;
short StructMember2;
byte StructMember3[8] ;
}Struct_736_t;
typedef struct Struct_1066_t
{
 short StructMember0;
long StructMember1;
long StructMember2;
}Struct_1066_t;
typedef struct Struct_1338_t
{
long StructMember0;
long StructMember1;
}Struct_1338_t;
typedef struct Struct_1618_t
{
long StructMember0;
}Struct_1618_t;
typedef struct Struct_1662_t
{
[range(0,131088)]  long StructMember0;
[range(0,131088)]  long StructMember1;
[unique]  /* [DBG]  FC_CVARRAY */[size_is(StructMember1)] [length_is(StructMember0)] char *StructMember2/*[]  CONFORMANT_ARRAY*/;
}Struct_1662_t;
typedef struct Struct_1880_t
{
[range(0,65536)]  long StructMember0;
[unique] [size_is(StructMember0)] char *StructMember1;
}Struct_1880_t;
typedef struct Struct_2002_t
{
long StructMember0;
}Struct_2002_t;
typedef struct Struct_2576_t
{
long StructMember0;
[unique] [size_is(StructMember0)] char *StructMember1;
}Struct_2576_t;
typedef struct Struct_2698_t
{
[range(0,0)]  long StructMember0;
[unique] [size_is(StructMember0)] char *StructMember1;
}Struct_2698_t;
typedef struct Struct_2924_t
{
 short StructMember0;
long StructMember1;
long StructMember2;
long StructMember3;
}Struct_2924_t;
typedef struct Struct_3012_t
{
long StructMember0;
long StructMember1;
}Struct_3012_t;
typedef struct Struct_3090_t
{
[unique] [string]  wchar_t* StructMember0;
long StructMember1;
[range(0,256)]  long StructMember2;
[unique] [size_is(StructMember2)] char *StructMember3;
}Struct_3090_t;
typedef struct Struct_3392_t
{
[unique] [string] [size_is(337)]  wchar_t* StructMember0;
[unique] [string] [size_is(337)]  wchar_t* StructMember1;
[unique] [string] [size_is(337)]  wchar_t* StructMember2;
[unique] [string] [size_is(337)]  wchar_t* StructMember3;
[unique] [string] [size_is(337)]  wchar_t* StructMember4;
[unique] [string] [size_is(337)]  wchar_t* StructMember5;
[unique] [string] [size_is(256)]  wchar_t* StructMember6;
long StructMember7;
[range(0,1007)]  long StructMember8;
[unique] [size_is(StructMember8)] long *StructMember9;
}Struct_3392_t;
typedef struct Struct_3688_t
{
short StructMember0;
short StructMember1;
short StructMember2;
}Struct_3688_t;
typedef struct Struct_3904_t
{
char StructMember0[128] ;
}Struct_3904_t;
typedef [switch_type(/* enum_16 */ short )] union union_3924
{
[case(6)] long unionMember_6;
[default] 
unsigned __int3264 defaultMember;
}union_3924;
typedef struct Struct_4032_t
{
short StructMember0;
short StructMember1;
[unique]  /* [DBG]  FC_CVARRAY */[size_is(StructMember1/2)] [length_is(StructMember0/2)] short *StructMember2/*[]  CONFORMANT_ARRAY*/;
}Struct_4032_t;
typedef struct Struct_4146_t
{
[range(0,131072)]  long StructMember0;
[unique] [size_is(StructMember0)] char *StructMember1;
}Struct_4146_t;
typedef struct Struct_5134_t
{
 short StructMember0;
}Struct_5134_t;
typedef struct Struct_5486_t
{
[range(0,262144)]  long StructMember0;
[unique] [size_is(StructMember0)] char *StructMember1;
}Struct_5486_t;
typedef struct Struct_280_t
{
char StructMember0;
char StructMember1;
struct Struct_258_t StructMember2;
[size_is(StructMember1)] long StructMember3[] ;
}Struct_280_t;
typedef struct Struct_524_t
{
long StructMember0;
long StructMember1;
struct Struct_518_t StructMember2;
char StructMember3;
struct Struct_518_t StructMember4;
long StructMember5;
}Struct_524_t;
typedef struct Struct_628_t
{
struct Struct_44_t StructMember0;
}Struct_628_t;
typedef struct Struct_652_t
{
struct Struct_44_t StructMember0;
struct Struct_44_t StructMember1;
}Struct_652_t;
typedef struct Struct_670_t
{
unsigned __int3264 StructMember0;
unsigned __int3264 StructMember1;
unsigned __int3264 StructMember2;
unsigned __int3264 StructMember3;
unsigned __int3264 StructMember4;
struct Struct_518_t StructMember5;
}Struct_670_t;
typedef struct Struct_688_t
{
struct Struct_670_t StructMember0;
}Struct_688_t;
typedef struct Struct_702_t
{
struct Struct_518_t StructMember0;
struct Struct_518_t StructMember1;
}Struct_702_t;
typedef struct Struct_828_t
{
[unique] struct Struct_280_t* StructMember0;
}Struct_828_t;
typedef struct Struct_864_t
{
long StructMember0;
[unique]  /* [DBG]  FC_BOGUS_ARRAY */ [size_is(StructMember0)]  /*  */ struct Struct_828_t* StructMember1;
}Struct_864_t;
typedef struct Struct_1100_t
{
[range(0,1000)]  long StructMember0;
[unique]  /* [DBG]  FC_BOGUS_ARRAY */ [size_is(StructMember0)]  /*  */ struct Struct_1066_t* StructMember1;
}Struct_1100_t;
typedef struct Struct_1142_t
{
[unique] struct Struct_280_t* StructMember0;
}Struct_1142_t;
typedef struct Struct_1178_t
{
[range(0,20480)]  long StructMember0;
[unique]  /* [DBG]  FC_BOGUS_ARRAY */ [size_is(StructMember0)]  /*  */ struct Struct_1142_t* StructMember1;
}Struct_1178_t;
typedef struct Struct_1220_t
{
 short StructMember0;
struct Struct_44_t StructMember1;
long StructMember2;
}Struct_1220_t;
typedef struct Struct_1260_t
{
[range(0,20480)]  long StructMember0;
[unique]  /* [DBG]  FC_BOGUS_ARRAY */ [size_is(StructMember0)]  /*  */ struct Struct_1220_t* StructMember1;
}Struct_1260_t;
typedef struct Struct_1346_t
{
struct Struct_1338_t StructMember0;
long StructMember1;
}Struct_1346_t;
typedef struct Struct_1372_t
{
[range(0,1000)]  long StructMember0;
long StructMember1;
[size_is(StructMember0)] struct Struct_1346_t StructMember2[] ;
}Struct_1372_t;
typedef struct Struct_1552_t
{
struct Struct_44_t StructMember0;
}Struct_1552_t;
typedef struct Struct_1598_t
{
[range(0,5)]  long StructMember0;
[unique]  /* [DBG]  FC_BOGUS_ARRAY */ [size_is(StructMember0)]  /*  */ struct Struct_44_t* StructMember1;
}Struct_1598_t;
typedef struct Struct_1684_t
{
[unique] struct Struct_1662_t* StructMember0;
[unique] struct Struct_1662_t* StructMember1;
}Struct_1684_t;
typedef struct Struct_1772_t
{
struct Struct_518_t StructMember0;
long StructMember1;
[range(0,65536)]  long StructMember2;
[unique] [size_is(StructMember2)] char *StructMember3;
}Struct_1772_t;
typedef struct Struct_1796_t
{
[range(0,1)]  long StructMember0;
[unique] struct Struct_1772_t* StructMember1;
[unique] struct Struct_1772_t* StructMember2;
[range(0,1)]  long StructMember3;
[unique] struct Struct_1772_t* StructMember4;
[unique] struct Struct_1772_t* StructMember5;
}Struct_1796_t;
typedef struct Struct_1900_t
{
struct Struct_1880_t StructMember0;
}Struct_1900_t;
typedef struct Struct_2194_t
{
[range(0,256)]  long StructMember0;
[unique]  /* [DBG]  FC_BOGUS_ARRAY */ [size_is(StructMember0)]  /*  */ struct Struct_44_t* StructMember1;
}Struct_2194_t;
typedef struct Struct_2592_t
{
long StructMember0;
struct Struct_518_t StructMember1;
struct Struct_518_t StructMember2;
struct Struct_518_t StructMember3;
struct Struct_518_t StructMember4;
struct Struct_518_t StructMember5;
}Struct_2592_t;
typedef struct Struct_2740_t
{
[range(0,0)]  long StructMember0;
[unique]  /* [DBG]  FC_BOGUS_ARRAY */ [size_is(StructMember0)]  /*  */ struct Struct_2698_t* StructMember1;
}Struct_2740_t;
typedef struct Struct_2798_t
{
 short StructMember0;
struct Struct_44_t StructMember1;
long StructMember2;
long StructMember3;
}Struct_2798_t;
typedef struct Struct_2838_t
{
[range(0,20480)]  long StructMember0;
[unique]  /* [DBG]  FC_BOGUS_ARRAY */ [size_is(StructMember0)]  /*  */ struct Struct_2798_t* StructMember1;
}Struct_2838_t;
typedef struct Struct_2960_t
{
[range(0,1000)]  long StructMember0;
[unique]  /* [DBG]  FC_BOGUS_ARRAY */ [size_is(StructMember0)]  /*  */ struct Struct_2924_t* StructMember1;
}Struct_2960_t;
typedef struct Struct_3568_t
{
 short StructMember0;
[unique] struct Struct_280_t* StructMember1;
long StructMember2;
long StructMember3;
}Struct_3568_t;
typedef struct Struct_3608_t
{
[range(0,1000)]  long StructMember0;
[unique]  /* [DBG]  FC_BOGUS_ARRAY */ [size_is(StructMember0)]  /*  */ struct Struct_3568_t* StructMember1;
}Struct_3608_t;
typedef [switch_type(unsigned small )] union union_3676
{
[case(1)] struct Struct_3688_t unionMember_1;
}union_3676;
typedef struct Struct_3820_t
{
char StructMember0;
char StructMember1;
struct Struct_258_t StructMember2;
[size_is(StructMember1)] long StructMember3[] ;
}Struct_3820_t;
typedef struct Struct_3842_t
{
struct Struct_736_t StructMember0;
short StructMember1;
short StructMember2;
long StructMember3;
}Struct_3842_t;
typedef struct Struct_3876_t
{
short StructMember0;
short StructMember1;
[unique]  /* [DBG]  FC_BOGUS_ARRAY */ [size_is(StructMember0)]  /*  */ struct Struct_3842_t* StructMember2;
}Struct_3876_t;
typedef struct Struct_4248_t
{
long StructMember0;
 short StructMember1;
long StructMember2;
struct Struct_4032_t StructMember3;
}Struct_4248_t;
typedef struct Struct_4288_t
{
long StructMember0;
[unique]  /* [DBG]  FC_BOGUS_ARRAY */ [size_is(StructMember0)]  /*  */ struct Struct_4248_t** StructMember1;
}Struct_4288_t;
typedef struct Struct_4502_t
{
struct Struct_736_t StructMember0;
long StructMember1;
struct Struct_736_t StructMember2;
}Struct_4502_t;
typedef struct Struct_4640_t
{
char StructMember0;
char StructMember1;
struct Struct_258_t StructMember2;
[size_is(StructMember1)] long StructMember3[] ;
}Struct_4640_t;
typedef struct Struct_4676_t
{
long StructMember0;
[unique]  /* [DBG]  FC_BOGUS_ARRAY */ [size_is(StructMember0)]  /*  */ struct Struct_4640_t** StructMember1;
}Struct_4676_t;
typedef struct Struct_4726_t
{
[unique]  /* [DBG]  FC_BOGUS_ARRAY */ [size_is(StructMember1)]  /*  */ struct Struct_736_t* StructMember0;
long StructMember1;
}Struct_4726_t;
typedef struct Struct_4780_t
{
[unique]  /* [DBG]  FC_BOGUS_ARRAY */ [size_is(StructMember1)]  /*  */ struct Struct_736_t* StructMember0;
long StructMember1;
}Struct_4780_t;
typedef struct Struct_5022_t
{
struct Struct_4032_t StructMember0;
struct Struct_4032_t StructMember1;
}Struct_5022_t;
typedef [switch_type(/* enum_16 */ short )] union union_5110
{
[case(0)] struct Struct_5134_t unionMember_0;
[case(1)] struct Struct_5134_t unionMember_1;
[case(2)] struct Struct_5134_t unionMember_2;
}union_5110;
typedef struct Struct_70_t
{
struct Struct_44_t StructMember0;
struct Struct_62_t StructMember1;
}Struct_70_t;
typedef struct Struct_316_t
{
char StructMember0;
char StructMember1;
short StructMember2;
[unique] struct Struct_280_t* StructMember3;
[unique] struct Struct_280_t* StructMember4;
[unique] struct Struct_306_t* StructMember5;
[unique] struct Struct_306_t* StructMember6;
}Struct_316_t;
typedef struct Struct_592_t
{
struct Struct_44_t StructMember0;
[unique] struct Struct_280_t* StructMember1;
}Struct_592_t;
typedef struct Struct_610_t
{
struct Struct_44_t StructMember0;
[unique] struct Struct_280_t* StructMember1;
}Struct_610_t;
typedef struct Struct_888_t
{
struct Struct_44_t StructMember0;
[unique] struct Struct_280_t* StructMember1;
}Struct_888_t;
typedef struct Struct_1704_t
{
struct Struct_44_t StructMember0;
struct Struct_44_t StructMember1;
[unique] struct Struct_280_t* StructMember2;
long StructMember3;
long StructMember4;
long StructMember5;
}Struct_1704_t;
typedef struct Struct_1948_t
{
struct Struct_44_t StructMember0;
struct Struct_44_t StructMember1;
[unique] struct Struct_280_t* StructMember2;
long StructMember3;
long StructMember4;
long StructMember5;
long StructMember6;
[unique] [size_is(StructMember6)] char *StructMember7;
}Struct_1948_t;
typedef [switch_type(/* enum_16 */ short )] union union_2546
{
[case(2)] struct Struct_2576_t unionMember_2;
[case(3)] struct Struct_2592_t unionMember_3;
}union_2546;
typedef struct Struct_3152_t
{
long StructMember0;
long StructMember1;
[unique] [string] [size_is(32767)]  wchar_t* StructMember2;
[unique] [string] [size_is(256)]  wchar_t* StructMember3;
struct Struct_3012_t StructMember4;
[range(0,2560)]  long StructMember5;
[unique] [size_is(StructMember5)] char *StructMember6;
long StructMember7;
[range(0,64)]  long StructMember8;
[unique]  /* [DBG]  FC_BOGUS_ARRAY */ [size_is(StructMember8)]  /*  */ struct Struct_3090_t* StructMember9;
[unique] [string] [size_is(256)]  wchar_t* StructMember10;
[unique] [string] [size_is(513)]  wchar_t* StructMember11;
}Struct_3152_t;
typedef struct Struct_3696_t
{
long StructMember0;
long StructMember1;
long StructMember2;
unsigned __int3264 StructMember3;
struct Struct_62_t StructMember4;
[switch_is(StructMember0)] union union_3676 StructMember5;
}Struct_3696_t;
typedef struct Struct_4102_t
{
[unique] struct Struct_3820_t* StructMember0;
struct Struct_4032_t StructMember1;
struct Struct_4032_t StructMember2;
}Struct_4102_t;
typedef struct Struct_4998_t
{
struct Struct_4032_t StructMember0;
struct Struct_4032_t StructMember1;
[ref] struct Struct_3820_t* StructMember2;
long StructMember3;
}Struct_4998_t;
typedef struct Struct_5556_t
{
struct Struct_4032_t StructMember0;
struct Struct_4032_t StructMember1;
struct Struct_4032_t StructMember2;
struct Struct_4032_t StructMember3;
struct Struct_518_t StructMember4;
}Struct_5556_t;
typedef struct Struct_364_t
{
long StructMember0;
[unique] char *StructMember1;
[unique] struct Struct_234_t* StructMember2;
long StructMember3;
[unique] struct Struct_316_t* StructMember4;
[unique] struct Struct_350_t* StructMember5;
}Struct_364_t;
typedef struct Struct_748_t
{
struct Struct_44_t StructMember0;
struct Struct_44_t StructMember1;
struct Struct_44_t StructMember2;
struct Struct_736_t StructMember3;
[unique] struct Struct_280_t* StructMember4;
}Struct_748_t;
typedef struct Struct_1836_t
{
struct Struct_1704_t StructMember0;
struct Struct_1618_t StructMember1;
struct Struct_1796_t StructMember2;
}Struct_1836_t;
typedef struct Struct_1914_t
{
struct Struct_1704_t StructMember0;
struct Struct_1618_t StructMember1;
struct Struct_1900_t StructMember2;
}Struct_1914_t;
typedef struct Struct_1980_t
{
struct Struct_1948_t StructMember0;
struct Struct_1618_t StructMember1;
struct Struct_1796_t StructMember2;
}Struct_1980_t;
typedef [switch_type(/* enum_16 */ short )] union union_4078
{
[case(0)] struct Struct_4032_t unionMember_0;
[case(1)] struct Struct_4032_t unionMember_1;
[case(2)] struct Struct_4102_t unionMember_2;
[default] 
struct Struct_4146_t defaultMember;
}union_4078;
typedef [switch_type(/* enum_16 */ short )] union union_3746
{
[case(2)] [unique] [string]  wchar_t* unionMember_2;
[case(3)] unsigned __int3264 unionMember_3;
[case(4)] unsigned __int3264 unionMember_4;
[case(5)] [unique] struct Struct_3820_t* unionMember_5;
[case(9)] [unique] struct Struct_736_t* unionMember_9;
[case(6)] long unionMember_6;
[case(7)] [unique] struct Struct_3876_t* unionMember_7;
[case(12)] [unique] struct Struct_3904_t* unionMember_12;
[default] 
unsigned __int3264 defaultMember;
}union_3746;
typedef [switch_type(/* enum_16 */ short )] union union_428
{
[case(1)] struct Struct_524_t unionMember_1;
[case(2)] struct Struct_570_t unionMember_2;
[case(3)] struct Struct_592_t unionMember_3;
[case(5)] struct Struct_610_t unionMember_5;
[case(4)] struct Struct_628_t unionMember_4;
[case(6)] struct Struct_642_t unionMember_6;
[case(7)] struct Struct_652_t unionMember_7;
[case(8)] struct Struct_688_t unionMember_8;
[case(9)] struct Struct_702_t unionMember_9;
[case(10)] struct Struct_716_t unionMember_10;
[case(11)] struct Struct_722_t unionMember_11;
[case(12)] struct Struct_748_t unionMember_12;
[case(13)] struct Struct_748_t unionMember_13;
[case(14)] struct Struct_610_t unionMember_14;
}union_428;
typedef [switch_type(/* enum_16 */ short )] union union_1468
{
[case(1)] struct Struct_1552_t unionMember_1;
[case(2)] struct Struct_1598_t unionMember_2;
[case(3)] struct Struct_1618_t unionMember_3;
[case(4)] struct Struct_1684_t unionMember_4;
[case(5)] struct Struct_888_t unionMember_5;
[case(6)] struct Struct_1704_t unionMember_6;
[case(7)] struct Struct_1796_t unionMember_7;
[case(8)] struct Struct_1836_t unionMember_8;
[case(9)] struct Struct_1900_t unionMember_9;
[case(10)] struct Struct_1914_t unionMember_10;
[case(11)] struct Struct_1948_t unionMember_11;
[case(12)] struct Struct_1980_t unionMember_12;
[case(13)] struct Struct_2002_t unionMember_13;
}union_1468;
typedef struct Struct_110_t
{
long StructMember0;
[unique]  /* [DBG]  FC_BOGUS_ARRAY */ [size_is(StructMember0)]  /*  */ struct Struct_70_t* StructMember1;
}Struct_110_t;
typedef struct Struct_948_t
{
long StructMember0;
[unique]  /* [DBG]  FC_BOGUS_ARRAY */ [size_is(StructMember0)]  /*  */ struct Struct_888_t* StructMember1;
}Struct_948_t;
typedef struct Struct_1034_t
{
long StructMember0;
[unique]  /* [DBG]  FC_BOGUS_ARRAY */ [size_is(StructMember0)]  /*  */ struct Struct_888_t* StructMember1;
long StructMember2;
}Struct_1034_t;
typedef struct Struct_2480_t
{
long StructMember0;
[unique]  /* [DBG]  FC_BOGUS_ARRAY */ [size_is(StructMember0)]  /*  */ struct Struct_1704_t* StructMember1;
}Struct_2480_t;
typedef struct Struct_3208_t
{
struct Struct_3152_t StructMember0;
long StructMember1;
}Struct_3208_t;
typedef struct Struct_3290_t
{
long StructMember0;
[unique]  /* [DBG]  FC_BOGUS_ARRAY */ [size_is(StructMember0)]  /*  */ struct Struct_3208_t** StructMember1;
}Struct_3290_t;
typedef struct Struct_5072_t
{
[range(1,4096)]  long StructMember0;
[ref]  /* [DBG]  FC_BOGUS_ARRAY */ [size_is(StructMember0)]  /*  */ struct Struct_4998_t* StructMember1;
}Struct_5072_t;
typedef struct Struct_5608_t
{
[range(0,1000)]  long StructMember0;
[unique]  /* [DBG]  FC_BOGUS_ARRAY */ [size_is(StructMember0)]  /*  */ struct Struct_5556_t** StructMember1;
}Struct_5608_t;
typedef struct Struct_3936_t
{
 short StructMember0;
long StructMember1;
long StructMember2;
[switch_is(StructMember0)] union union_3746 StructMember3;
[switch_is(StructMember0)] union union_3924 StructMember4;
}Struct_3936_t;
typedef struct Struct_4166_t
{
long StructMember0;
 short StructMember1;
struct Struct_518_t StructMember2;
[switch_is(StructMember1)] union union_4078 StructMember3;
}Struct_4166_t;
typedef [switch_type(/* enum_16 */ short )] union union_4974
{
[case(0)] struct Struct_4998_t unionMember_0;
[case(1)] struct Struct_5022_t unionMember_1;
[case(2)] struct Struct_5072_t unionMember_2;
}union_4974;
typedef struct Struct_3980_t
{
long StructMember0;
long StructMember1;
short StructMember2;
[unique]  /* [DBG]  FC_BOGUS_ARRAY */ [size_is(StructMember2)]  /*  */ struct Struct_3936_t* StructMember3;
}Struct_3980_t;
typedef struct Struct_4208_t
{
[range(0,4000)]  long StructMember0;
[unique]  /* [DBG]  FC_BOGUS_ARRAY */ [size_is(StructMember0)]  /*  */ struct Struct_4166_t** StructMember1;
}Struct_4208_t;
long Proc0_LsarClose(
[in][out]/* simple_ref */[context_handle] void** arg_0);

long Proc1_CredrRename(
[in][context_handle] void* arg_0);

long Proc2_LsarEnumeratePrivileges(
[in][context_handle] void* arg_0,
[in][out]/* simple_ref */long *arg_1,
[out]/* simple_ref */struct Struct_110_t* arg_2,
[in]long arg_3);

long Proc3_LsarQuerySecurityObject(
[in][context_handle] void* arg_0,
[in]long arg_1,
[out][ref]struct Struct_160_t** arg_2);

long Proc4_LsarSetSecurityObject(
[in][context_handle] void* arg_0,
[in]long arg_1,
[in]/* simple_ref */struct Struct_160_t* arg_2);

long Proc5_LsaITestCall(
[in]/* simple_ref */struct Struct_44_t* arg_0,
[in]/* simple_ref */struct Struct_44_t* arg_1,
[in]/* simple_ref */struct Struct_44_t* arg_2,
[in]/* simple_ref */struct Struct_44_t* arg_3,
[in]/* simple_ref */struct Struct_44_t* arg_4);

long Proc6_LsarOpenPolicyRPC(
[in][unique]wchar_t *arg_0,
[in]/* simple_ref */struct Struct_364_t* arg_1,
[in]long arg_2,
[out]/* simple_ref */[context_handle] void** arg_3);

long Proc7_LsarQueryInformationPolicy(
[in][context_handle] void* arg_0,
[in]/* enum_16 */ short arg_1,
[out][ref][switch_is(arg_1)]union union_428** arg_2);

long Proc8_LsarSetInformationPolicy(
[in][context_handle] void* arg_0,
[in]/* enum_16 */ short arg_1,
[in]/* simple_ref */[switch_is(arg_1)]union union_428* arg_2);

long Proc9_LsaITestCall(
[in][context_handle] void* arg_0);

long Proc10_LsarCreateAccount(
[in][context_handle] void* arg_0,
[in]/* simple_ref */struct Struct_280_t* arg_1,
[in]long arg_2,
[out]/* simple_ref */[context_handle] void** arg_3);

long Proc11_LsarEnumerateAccounts(
[in][context_handle] void* arg_0,
[in][out]/* simple_ref */long *arg_1,
[out]/* simple_ref */struct Struct_864_t* arg_2,
[in]long arg_3);

long Proc12_LsarCreateTrustedDomain(
[in][context_handle] void* arg_0,
[in]/* simple_ref */struct Struct_888_t* arg_1,
[in]long arg_2,
[out]/* simple_ref */[context_handle] void** arg_3);

long Proc13_LsarEnumerateTrustedDomains(
[in][context_handle] void* arg_0,
[in][out]/* simple_ref */long *arg_1,
[out]/* simple_ref */struct Struct_948_t* arg_2,
[in]long arg_3);

long Proc14_LsarLookupNames(
[in][context_handle] void* arg_0,
[in][range(0,1000)] long arg_1,
[in]/* simple_ref */ /* [DBG] FC_BOGUS_ARRAY */ [size_is(arg_1)] /*  */ struct Struct_44_t* arg_2,
[out][ref]struct Struct_1034_t** arg_3,
[in][out]/* simple_ref */struct Struct_1100_t* arg_4,
[in]/* enum_16 */ short arg_5,
[in][out]/* simple_ref */long *arg_6);

long Proc15_LsarLookupSids(
[in][context_handle] void* arg_0,
[in]/* simple_ref */struct Struct_1178_t* arg_1,
[out][ref]struct Struct_1034_t** arg_2,
[in][out]/* simple_ref */struct Struct_1260_t* arg_3,
[in]/* enum_16 */ short arg_4,
[in][out]/* simple_ref */long *arg_5);

long Proc16_LsarCreateSecret(
[in][context_handle] void* arg_0,
[in]/* simple_ref */struct Struct_44_t* arg_1,
[in]long arg_2,
[out]/* simple_ref */[context_handle] void** arg_3);

long Proc17_LsarOpenAccount(
[in][context_handle] void* arg_0,
[in]/* simple_ref */struct Struct_280_t* arg_1,
[in]long arg_2,
[out]/* simple_ref */[context_handle] void** arg_3);

long Proc18_LsarEnumeratePrivilegesAccount(
[in][context_handle] void* arg_0,
[out][ref]struct Struct_1372_t** arg_1);

long Proc19_LsarAddPrivilegesToAccount(
[in][context_handle] void* arg_0,
[in]/* simple_ref */struct Struct_1372_t* arg_1);

long Proc20_LsarRemovePrivilegesFromAccount(
[in][context_handle] void* arg_0,
[in]char arg_1,
[in][unique]struct Struct_1372_t* arg_2);

long Proc21_LsarGetQuotasForAccount(
[in][context_handle] void* arg_0,
[out]/* simple_ref */struct Struct_670_t* arg_1);

long Proc22_LsaAllocateSharedMemory(
[in][context_handle] void* arg_0,
[in]/* simple_ref */struct Struct_670_t* arg_1);

long Proc23_LsarGetSystemAccessAccount(
[in][context_handle] void* arg_0,
[out]/* simple_ref */long *arg_1);

long Proc24_LsarSetSystemAccessAccount(
[in][context_handle] void* arg_0,
[in]long arg_1);

long Proc25_LsarOpenTrustedDomain(
[in][context_handle] void* arg_0,
[in]/* simple_ref */struct Struct_280_t* arg_1,
[in]long arg_2,
[out]/* simple_ref */[context_handle] void** arg_3);

long Proc26_LsarQueryInfoTrustedDomain(
[in][context_handle] void* arg_0,
[in]/* enum_16 */ short arg_1,
[out][ref][switch_is(arg_1)]union union_1468** arg_2);

long Proc27_LsarSetInformationTrustedDomain(
[in][context_handle] void* arg_0,
[in]/* enum_16 */ short arg_1,
[in]/* simple_ref */[switch_is(arg_1)]union union_1468* arg_2);

long Proc28_LsarOpenSecret(
[in][context_handle] void* arg_0,
[in]/* simple_ref */struct Struct_44_t* arg_1,
[in]long arg_2,
[out]/* simple_ref */[context_handle] void** arg_3);

long Proc29_LsarSetSecret(
[in][context_handle] void* arg_0,
[in][unique]struct Struct_1662_t* arg_1,
[in][unique]struct Struct_1662_t* arg_2);

long Proc30_LsarQuerySecret(
[in][context_handle] void* arg_0,
[in][out][unique]struct Struct_1662_t** arg_1,
[in][out][unique]struct Struct_518_t* arg_2,
[in][out][unique]struct Struct_1662_t** arg_3,
[in][out][unique]struct Struct_518_t* arg_4);

long Proc31_LsarLookupPrivilegeValue(
[in][context_handle] void* arg_0,
[in]/* simple_ref */struct Struct_44_t* arg_1,
[out]/* simple_ref */struct Struct_62_t* arg_2);

long Proc32_LsarLookupPrivilegeName(
[in][context_handle] void* arg_0,
[in]/* simple_ref */struct Struct_62_t* arg_1,
[out][ref]struct Struct_44_t** arg_2);

long Proc33_LsarLookupPrivilegeDisplayName(
[in][context_handle] void* arg_0,
[in]/* simple_ref */struct Struct_44_t* arg_1,
[in]short arg_2,
[in]short arg_3,
[out][ref]struct Struct_44_t** arg_4,
[out]/* simple_ref */short *arg_5);

long Proc34_LsarDeleteObject(
[in][out]/* simple_ref */[context_handle] void** arg_0);

long Proc35_LsarEnumerateAccountsWithUserRight(
[in][context_handle] void* arg_0,
[in][unique]struct Struct_44_t* arg_1,
[out]/* simple_ref */struct Struct_864_t* arg_2);

long Proc36_LsarEnumerateAccountRights(
[in][context_handle] void* arg_0,
[in]/* simple_ref */struct Struct_280_t* arg_1,
[out]/* simple_ref */struct Struct_2194_t* arg_2);

long Proc37_LsarAddAccountRights(
[in][context_handle] void* arg_0,
[in]/* simple_ref */struct Struct_280_t* arg_1,
[in]/* simple_ref */struct Struct_2194_t* arg_2);

long Proc38_LsarRemoveAccountRights(
[in][context_handle] void* arg_0,
[in]/* simple_ref */struct Struct_280_t* arg_1,
[in]char arg_2,
[in]/* simple_ref */struct Struct_2194_t* arg_3);

long Proc39_LsarQueryTrustedDomainInfo(
[in][context_handle] void* arg_0,
[in]/* simple_ref */struct Struct_280_t* arg_1,
[in]/* enum_16 */ short arg_2,
[out][ref][switch_is(arg_2)]union union_1468** arg_3);

long Proc40_LsarSetTrustedDomainInfo(
[in][context_handle] void* arg_0,
[in]/* simple_ref */struct Struct_280_t* arg_1,
[in]/* enum_16 */ short arg_2,
[in]/* simple_ref */[switch_is(arg_2)]union union_1468* arg_3);

long Proc41_LsarDeleteTrustedDomain(
[in][context_handle] void* arg_0,
[in]/* simple_ref */struct Struct_280_t* arg_1);

long Proc42_LsarStorePrivateData(
[in][context_handle] void* arg_0,
[in]/* simple_ref */struct Struct_44_t* arg_1,
[in][unique]struct Struct_1662_t* arg_2);

long Proc43_LsarRetrievePrivateData(
[in][context_handle] void* arg_0,
[in]/* simple_ref */struct Struct_44_t* arg_1,
[in][out][ref]struct Struct_1662_t** arg_2);

long Proc44_LsarOpenPolicy2(
[in][unique][string] wchar_t* arg_0,
[in]/* simple_ref */struct Struct_364_t* arg_1,
[in]long arg_2,
[out]/* simple_ref */[context_handle] void** arg_3);

long Proc45_LsarGetUserName(
[in][unique][string] wchar_t* arg_0,
[in][out][ref]struct Struct_44_t** arg_1,
[in][out][unique]struct Struct_44_t** arg_2);

long Proc46_LsarQueryInformationPolicy2(
[in][context_handle] void* arg_0,
[in]/* enum_16 */ short arg_1,
[out][ref][switch_is(arg_1)]union union_428** arg_2);

long Proc47_LsarSetInformationPolicy2(
[in][context_handle] void* arg_0,
[in]/* enum_16 */ short arg_1,
[in]/* simple_ref */[switch_is(arg_1)]union union_428* arg_2);

long Proc48_LsarQueryTrustedDomainInfoByName(
[in][context_handle] void* arg_0,
[in]/* simple_ref */struct Struct_44_t* arg_1,
[in]/* enum_16 */ short arg_2,
[out][ref][switch_is(arg_2)]union union_1468** arg_3);

long Proc49_LsarSetTrustedDomainInfoByName(
[in][context_handle] void* arg_0,
[in]/* simple_ref */struct Struct_44_t* arg_1,
[in]/* enum_16 */ short arg_2,
[in]/* simple_ref */[switch_is(arg_2)]union union_1468* arg_3);

long Proc50_LsarEnumerateTrustedDomainsEx(
[in][context_handle] void* arg_0,
[in][out]/* simple_ref */long *arg_1,
[out]/* simple_ref */struct Struct_2480_t* arg_2,
[in]long arg_3);

long Proc51_LsarCreateTrustedDomainEx(
[in][context_handle] void* arg_0,
[in]/* simple_ref */struct Struct_1704_t* arg_1,
[in]/* simple_ref */struct Struct_1796_t* arg_2,
[in]long arg_3,
[out]/* simple_ref */[context_handle] void** arg_4);

long Proc52_LsaITestCall(
[in][out]/* simple_ref */[context_handle] void** arg_0);

long Proc53_LsarQueryDomainInformationPolicy(
[in][context_handle] void* arg_0,
[in]/* enum_16 */ short arg_1,
[out][ref][switch_is(arg_1)]union union_2546** arg_2);

long Proc54_LsarSetDomainInformationPolicy(
[in][context_handle] void* arg_0,
[in]/* enum_16 */ short arg_1,
[in][unique][switch_is(arg_1)]union union_2546* arg_2);

long Proc55_LsarOpenTrustedDomainByName(
[in][context_handle] void* arg_0,
[in]/* simple_ref */struct Struct_44_t* arg_1,
[in]long arg_2,
[out]/* simple_ref */[context_handle] void** arg_3);

long Proc56_LsaITestCall(
[in][context_handle] void* arg_0,
[in]/* enum_16 */ short arg_1,
[in]/* simple_ref */struct Struct_2740_t* arg_2,
[out][ref]struct Struct_2740_t** arg_3);

long Proc57_LsarLookupSids2(
[in][context_handle] void* arg_0,
[in]/* simple_ref */struct Struct_1178_t* arg_1,
[out][ref]struct Struct_1034_t** arg_2,
[in][out]/* simple_ref */struct Struct_2838_t* arg_3,
[in]/* enum_16 */ short arg_4,
[in][out]/* simple_ref */long *arg_5,
[in]long arg_6,
[in]long arg_7);

long Proc58_LsarLookupNames2(
[in][context_handle] void* arg_0,
[in][range(0,1000)] long arg_1,
[in]/* simple_ref */ /* [DBG] FC_BOGUS_ARRAY */ [size_is(arg_1)] /*  */ struct Struct_44_t* arg_2,
[out][ref]struct Struct_1034_t** arg_3,
[in][out]/* simple_ref */struct Struct_2960_t* arg_4,
[in]/* enum_16 */ short arg_5,
[in][out]/* simple_ref */long *arg_6,
[in]long arg_7,
[in]long arg_8);

long Proc59_LsarCreateTrustedDomainEx2(
[in][context_handle] void* arg_0,
[in]/* simple_ref */struct Struct_1704_t* arg_1,
[in]/* simple_ref */struct Struct_1900_t* arg_2,
[in]long arg_3,
[out]/* simple_ref */[context_handle] void** arg_4);

long Proc60_CredrWrite(
[in][unique][string] wchar_t* arg_0,
[in][ref]struct Struct_3208_t* arg_1,
[in]long arg_2);

long Proc61_CredrRead(
[in][unique][string] wchar_t* arg_0,
[in]/* simple_ref */[string][size_is(32767)] wchar_t* arg_1,
[in]long arg_2,
[in]long arg_3,
[out][ref]struct Struct_3208_t** arg_4);

long Proc62_CredrEnumerate(
[in][unique][string] wchar_t* arg_0,
[in][unique][string][size_is(32767)] wchar_t* arg_1,
[in]long arg_2,
[out]/* simple_ref */struct Struct_3290_t* arg_3);

long Proc63_CredrWriteDomainCredentials(
[in][unique][string] wchar_t* arg_0,
[in][ref]struct Struct_3392_t* arg_1,
[in][ref]struct Struct_3208_t* arg_2,
[in]long arg_3);

long Proc64_CredrReadDomainCredentials(
[in][unique][string] wchar_t* arg_0,
[in][ref]struct Struct_3392_t* arg_1,
[in]long arg_2,
[out]/* simple_ref */struct Struct_3290_t* arg_3);

long Proc65_CredrDelete(
[in][unique][string] wchar_t* arg_0,
[in]/* simple_ref */[string][size_is(32767)] wchar_t* arg_1,
[in]long arg_2,
[in]long arg_3);

long Proc66_CredrGetTargetInfo(
[in][unique][string] wchar_t* arg_0,
[in]/* simple_ref */[string][size_is(337)] wchar_t* arg_1,
[in]long arg_2,
[out][ref]struct Struct_3392_t** arg_3);

long Proc67_CredrProfileLoaded(
[in][unique][string] wchar_t* arg_0);

long Proc68_LsarLookupNames3(
[in][context_handle] void* arg_0,
[in][range(0,1000)] long arg_1,
[in]/* simple_ref */ /* [DBG] FC_BOGUS_ARRAY */ [size_is(arg_1)] /*  */ struct Struct_44_t* arg_2,
[out][ref]struct Struct_1034_t** arg_3,
[in][out]/* simple_ref */struct Struct_3608_t* arg_4,
[in]/* enum_16 */ short arg_5,
[in][out]/* simple_ref */long *arg_6,
[in]long arg_7,
[in]long arg_8);

long Proc69_CredrGetSessionTypes(
[in][unique][string] wchar_t* arg_0,
[in][range(0,1005)] long arg_1,
[out]/* simple_ref */[size_is(arg_1)]long *arg_2);

long Proc70_LsarRegisterAuditEvent(
[in]/* simple_ref */struct Struct_3696_t* arg_0,
[out]/* simple_ref */[context_handle] void** arg_1);

long Proc71_LsarGenAuditEvent(
[in][context_handle] void* arg_0,
[in]long arg_1,
[in]/* simple_ref */struct Struct_3980_t* arg_2);

long Proc72_LsarUnregisterAuditEvent(
[in][out]/* simple_ref */[context_handle] void** arg_0);

long Proc73_LsarQueryForestTrustInformation(
[in][context_handle] void* arg_0,
[in]/* simple_ref */struct Struct_4032_t* arg_1,
[in]/* enum_16 */ short arg_2,
[out][ref]struct Struct_4208_t** arg_3);

long Proc74_LsarSetForestTrustInformation(
[in][context_handle] void* arg_0,
[in]/* simple_ref */struct Struct_4032_t* arg_1,
[in]/* enum_16 */ short arg_2,
[in]/* simple_ref */struct Struct_4208_t* arg_3,
[in]char arg_4,
[out][ref]struct Struct_4288_t** arg_5);

long Proc75_CredrRename(
[in][unique][string] wchar_t* arg_0,
[in]/* simple_ref */[string][size_is(32767)] wchar_t* arg_1,
[in]/* simple_ref */[string][size_is(32767)] wchar_t* arg_2,
[in]long arg_3,
[in]long arg_4);

long Proc76_LsarLookupSids3(
[in]/* simple_ref */struct Struct_1178_t* arg_1,
[out][ref]struct Struct_1034_t** arg_2,
[in][out]/* simple_ref */struct Struct_2838_t* arg_3,
[in]/* enum_16 */ short arg_4,
[in][out]/* simple_ref */long *arg_5,
[in]long arg_6,
[in]long arg_7);

long Proc77_LsarLookupNames4(
[in][range(0,1000)] long arg_1,
[in]/* simple_ref */ /* [DBG] FC_BOGUS_ARRAY */ [size_is(arg_1)] /*  */ struct Struct_44_t* arg_2,
[out][ref]struct Struct_1034_t** arg_3,
[in][out]/* simple_ref */struct Struct_3608_t* arg_4,
[in]/* enum_16 */ short arg_5,
[in][out]/* simple_ref */long *arg_6,
[in]long arg_7,
[in]long arg_8);

long Proc78_LsarOpenPolicySce(
[in][unique]wchar_t *arg_0,
[in]/* simple_ref */struct Struct_364_t* arg_1,
[in]long arg_2,
[out]/* simple_ref */[context_handle] void** arg_3);

long Proc79_LsarAdtRegisterSecurityEventSource(
[in]long arg_0,
[in][unique][string] wchar_t* arg_1,
[out]/* simple_ref */[context_handle] void** arg_2);

long Proc80_LsarAdtUnregisterSecurityEventSource(
[in]long arg_0,
[in][out]/* simple_ref */[context_handle] void** arg_1);

long Proc81_LsarAdtReportSecurityEvent(
[in]long arg_0,
[in][context_handle] void* arg_1,
[in]long arg_2,
[in]/* simple_ref */struct Struct_3820_t* arg_3,
[in]/* simple_ref */struct Struct_3980_t* arg_4);

long Proc82_CredrFindBestCredential(
[in][unique][string] wchar_t* arg_0,
[in]/* simple_ref */[string][size_is(32767)] wchar_t* arg_1,
[in]long arg_2,
[in]long arg_3,
[out][ref]struct Struct_3208_t** arg_4);

long Proc83_LsarSetAuditPolicy(
[in][unique][string] wchar_t* arg_0,
[in][unique]struct Struct_280_t* arg_1,
[in][unique]struct Struct_736_t* arg_2,
[in][range(0,256)] long arg_3,
[in]/* simple_ref */ /* [DBG] FC_BOGUS_ARRAY */ [size_is(arg_3)] /*  */ struct Struct_4502_t* arg_4);

long Proc84_LsarQueryAuditPolicy(
[in][unique][string] wchar_t* arg_0,
[in][unique]struct Struct_280_t* arg_1,
[in][unique]struct Struct_736_t* arg_2,
[in][range(0,256)] long arg_3,
[in]/* simple_ref */ /* [DBG] FC_BOGUS_ARRAY */ [size_is(arg_3)] /*  */ struct Struct_736_t* arg_4,
[out][ref] /* [DBG] FC_BOGUS_ARRAY */ [size_is(arg_3)] /*  */ struct Struct_4502_t** arg_5);

long Proc85_LsarEnumerateAuditPolicy(
[in][unique][string] wchar_t* arg_0,
[out][ref]struct Struct_4676_t** arg_1);

long Proc86_LsarEnumerateAuditCategories(
[in][unique][string] wchar_t* arg_0,
[out][ref]struct Struct_4726_t** arg_1);

long Proc87_LsarEnumerateAuditSubCategories(
[in][unique][string] wchar_t* arg_0,
[in][unique]struct Struct_736_t* arg_1,
[in]char arg_2,
[out][ref]struct Struct_4780_t** arg_3);

long Proc88_LsarLookupAuditCategoryName(
[in][unique][string] wchar_t* arg_0,
[in]/* simple_ref */struct Struct_736_t* arg_1,
[out][ref]struct Struct_44_t** arg_2);

long Proc89_LsarLookupAuditSubCategoryName(
[in][unique][string] wchar_t* arg_0,
[in]/* simple_ref */struct Struct_736_t* arg_1,
[out][ref]struct Struct_44_t** arg_2);

long Proc90_LsarSetAuditSecurity(
[in][unique][string] wchar_t* arg_0,
[in]long arg_1,
[in]/* simple_ref */struct Struct_160_t* arg_2);

long Proc91_LsarQueryAuditSecurity(
[in][unique][string] wchar_t* arg_0,
[in]long arg_1,
[out][ref]struct Struct_160_t** arg_2);

long Proc92_CredrReadByTokenHandle(
[in][unique][string] wchar_t* arg_0,
[in]unsigned __int3264 arg_1,
[in]long arg_2,
[in]/* simple_ref */[string][size_is(32767)] wchar_t* arg_3,
[in]long arg_4,
[in]long arg_5,
[out][ref]struct Struct_3208_t** arg_6);

long Proc93_CredrRestoreCredentials(
[in][unique][string] wchar_t* arg_0,
[in][unique][string][size_is(260)] wchar_t* arg_1,
[in][unique][size_is(arg_3)]char *arg_2,
[in][range(0,1024)] long arg_3,
[in]long arg_4);

long Proc94_CredrBackupCredentials(
[in][unique][string] wchar_t* arg_0,
[in]unsigned __int3264 arg_1,
[in]long arg_2,
[in][unique][string][size_is(260)] wchar_t* arg_3,
[in][unique][size_is(arg_5)]char *arg_4,
[in][range(0,1024)] long arg_5,
[in]long arg_6);

long Proc95_LsarManageSidNameMapping(
[in][unique][string] wchar_t* arg_0,
[in]/* enum_16 */ short arg_1,
[in]/* simple_ref */[switch_is(arg_1)]union union_4974* arg_2,
[out][ref][switch_is(arg_1)]union union_5110** arg_3);

long Proc96_CredrProfileUnloaded(
[in][unique][string] wchar_t* arg_0);

long Proc97_CredrRename(
[in][unique][string] wchar_t* arg_0,
[in]/* simple_ref */[string][size_is(1041)] wchar_t* arg_1,
[in][unique][size_is(arg_3)]char *arg_2,
[in]long arg_3,
[in][unique][string][size_is(1041)] wchar_t* arg_4,
[in][unique][string][size_is(1041)] wchar_t* arg_5,
[in]long arg_6);

long Proc98_CredrRename(
[in][unique][string] wchar_t* arg_0,
[in]/* simple_ref */[string][size_is(1041)] wchar_t* arg_1,
[in]long arg_2,
[in][unique][string][size_is(1041)] wchar_t* arg_3,
[in][unique][string][size_is(1041)] wchar_t* arg_4,
[in][unique][string][size_is(1041)] wchar_t* arg_5,
[in][unique][string][size_is(1041)] wchar_t* arg_6);

long Proc99_CredrRename(
[in][unique][string] wchar_t* arg_0,
[in][unique][string][size_is(1041)] wchar_t* arg_1,
[in]/* simple_ref */[string][size_is(1041)] wchar_t* arg_2,
[in]long arg_3,
[in][unique][size_is(arg_5)]char *arg_4,
[in]long arg_5,
[in][unique][string][size_is(1041)] wchar_t* arg_6,
[in]long arg_7,
[in]long arg_8);

long Proc100_CredrRename(
[in][unique][string] wchar_t* arg_0,
[in]/* simple_ref */[string][size_is(1041)] wchar_t* arg_1,
[in]long arg_2,
[in][unique][string][size_is(1041)] wchar_t* arg_3,
[in][unique][string][size_is(1041)] wchar_t* arg_4,
[in][unique][string][size_is(1041)] wchar_t* arg_5);

long Proc101_CredrRename(
[in][unique][string] wchar_t* arg_0,
[in]/* simple_ref */[string][size_is(1041)] wchar_t* arg_1,
[out]/* simple_ref */long *arg_2);

long Proc102_LsarEfsGetSmartcardCredentials(
[in][unique][string] wchar_t* arg_0,
[in]/* simple_ref */struct Struct_62_t* arg_1,
[out][ref][size_is(, *arg_3)]char **arg_2,
[out]/* simple_ref */long *arg_3,
[out][ref][size_is(, *arg_5)]char **arg_4,
[out]/* simple_ref */long *arg_5);

long Proc103_LsarAuditSetGlobalSacl(
[in][unique][string] wchar_t* arg_0,
[in]/* simple_ref */struct Struct_4032_t* arg_1,
[in]/* simple_ref */struct Struct_5486_t* arg_2);

long Proc104_LsarAuditQueryGlobalSacl(
[in][unique][string] wchar_t* arg_0,
[in]/* simple_ref */struct Struct_4032_t* arg_1,
[out]/* simple_ref */struct Struct_5486_t* arg_2);

long Proc105_CredrProfileLoadedEx(
[in][unique][string] wchar_t* arg_0,
[in]long arg_1);

long Proc106_LsarInteractiveSessionIsLoggedOff(
[in][unique][string] wchar_t* arg_0,
[in]/* simple_ref */struct Struct_62_t* arg_1);

long Proc107_LsarConfigureAutoLogonCredentials(
[in][unique][string] wchar_t* arg_0);

long Proc108_LsarGetDeviceRegistrationInfo(
[in][unique][string] wchar_t* arg_0,
[out][ref]struct Struct_5608_t** arg_1);
}

