[
uuid(2acb9d68-b434-4b3e-b966-e06b4b3a84cb),
version(1.0),
]
interface DefaultIfName
{typedef struct Struct_14_t
{
long StructMember0;
long StructMember1;
}Struct_14_t;
typedef struct Struct_48_t
{
long StructMember0;
hyper StructMember1;
long StructMember2;
char StructMember3[248] ;
}Struct_48_t;
typedef [switch_type(/* enum_16 */ short )] union union_86
{
[case(3)] long unionMember_3;
[case(5)] long unionMember_5;
[case(4)] long unionMember_4;
[default] ;
}union_86;
typedef struct Struct_134_t
{
short StructMember0;
short StructMember1;
short StructMember2;
short StructMember3;
short StructMember4;
short StructMember5;
short StructMember6;
short StructMember7;
}Struct_134_t;
typedef struct Struct_154_t
{
long StructMember0;
hyper StructMember1;
long StructMember2;
long StructMember3;
long StructMember4;
long StructMember5;
struct Struct_134_t StructMember6;
struct Struct_134_t StructMember7;
wchar_t StructMember8[248] ;
}Struct_154_t;
typedef struct Struct_110_t
{
struct Struct_48_t StructMember0;
 short StructMember1;
 short StructMember2;
 short StructMember3;
[switch_is(/* FC_EXPR */(long)StructMember1)] union union_86 StructMember4;
}Struct_110_t;
error_status_t Proc0_BthServOpen(
[out]/* simple_ref */[context_handle] void** arg_1,
[out]/* simple_ref */long *arg_2,
[in]struct Struct_14_t arg_3);

error_status_t Proc1_BthServClose(
[in][out]/* simple_ref */[context_handle] void** arg_0,
[out]/* simple_ref */long *arg_1);

error_status_t Proc2_BthServRegisterAuthenticationEvent(
[in][context_handle] void* arg_0,
[out]/* simple_ref */long *arg_1,
[in]/* simple_ref */hyper *arg_2,
[in]hyper arg_3,
[in]long arg_4,
[in]long arg_5);

error_status_t Proc3_BthServDeregisterAuthenticationEvent(
[in][context_handle] void* arg_0,
[out]/* simple_ref */long *arg_1,
[in]/* simple_ref */hyper *arg_2,
[in]hyper arg_3);

error_status_t Proc4_BthServGetAuthRequest(
[in][context_handle] void* arg_0,
[out]/* simple_ref */long *arg_1,
[out]/* simple_ref */struct Struct_110_t* arg_2);

error_status_t Proc5_BthServGetDeviceInfo(
[in][context_handle] void* arg_0,
[out]/* simple_ref */long *arg_1,
[in]/* enum_16 */ short arg_2,
[in]/* simple_ref */hyper *arg_3,
[in][out]/* simple_ref */struct Struct_154_t* arg_4);

error_status_t Proc6_BthServSetDeviceName(
[in][context_handle] void* arg_0,
[out]/* simple_ref */long *arg_1,
[in]/* simple_ref */hyper *arg_2,
[in]wchar_t arg_3[248]);

error_status_t Proc7_BthServGetDeviceList(
[in][context_handle] void* arg_0,
[out]/* simple_ref */long *arg_1,
[in]long arg_2,
[in]char arg_3,
[in][range(0,268435456)] long arg_4,
[out][size_is(arg_4)]/*[range(0,268435456)]*/ char arg_5[],
[out]/* simple_ref */long *arg_6);

error_status_t Proc8_BthServActivateService(
[in][context_handle] void* arg_0,
[out]/* simple_ref */long *arg_1,
[in]/* simple_ref */hyper *arg_2,
[in][range(0,268435456)] long arg_3,
[in][size_is(arg_3)]/*[range(0,268435456)]*/ char arg_4[]);

error_status_t Proc9_BthServUpdateService(
[in][context_handle] void* arg_0,
[out]/* simple_ref */long *arg_1,
[in][range(0,268435456)] long arg_2,
[in][size_is(arg_2)]/*[range(0,268435456)]*/ char arg_3[],
[in]long arg_4);

error_status_t Proc10_BthServGetSdpRecord(
[in][context_handle] void* arg_0,
[out]/* simple_ref */long *arg_1,
[in]/* simple_ref */hyper *arg_2,
[in]/* enum_16 */ short arg_3,
[in]/* enum_16 */ short arg_4,
[in][range(0,268435456)] long arg_5,
[out][size_is(arg_5)]/*[range(0,268435456)]*/ char arg_6[],
[out]/* simple_ref */long *arg_7);

error_status_t Proc11_BthServSetSdpRecord(
[in][context_handle] void* arg_0,
[out]/* simple_ref */long *arg_1,
[in][range(0,268435456)] long arg_2,
[in][size_is(arg_2)]/*[range(0,268435456)]*/ char arg_3[],
[out]/* simple_ref */hyper *arg_4);

error_status_t Proc12_BthServSetSdpRecordWithInfo(
[in][context_handle] void* arg_0,
[out]/* simple_ref */long *arg_1,
[in]long arg_2,
[in]long arg_3,
[in]long arg_4,
[in][range(0,268435456)] long arg_5,
[in][size_is(arg_5)]/*[range(0,268435456)]*/ char arg_6[],
[out]/* simple_ref */hyper *arg_7);

error_status_t Proc13_BthServRemoveSdpRecord(
[in][context_handle] void* arg_0,
[out]/* simple_ref */long *arg_1,
[in]hyper arg_2);

error_status_t Proc14_BthServEnableDiscovery(
[in][context_handle] void* arg_0,
[out]/* simple_ref */long *arg_1,
[in]long arg_2);

error_status_t Proc15_BthServEnableIncomingConnections(
[in][context_handle] void* arg_0,
[out]/* simple_ref */long *arg_1,
[in]long arg_2);

error_status_t Proc16_BthServUninstallDevice(
[in][context_handle] void* arg_0,
[out]/* simple_ref */long *arg_1,
[in]wchar_t arg_2[62]);

error_status_t Proc17_BthServEirGetRecords(
[in][context_handle] void* arg_0,
[out]/* simple_ref */long *arg_1,
[in]/* simple_ref */hyper *arg_2,
[in]/* enum_16 */ short arg_3,
[in][range(0,268435456)] long arg_4,
[out][size_is(arg_4)]/*[range(0,268435456)]*/ char arg_5[],
[out]/* simple_ref */long *arg_6);

error_status_t Proc18_BthServEirSetRecord(
[in][context_handle] void* arg_0,
[out]/* simple_ref */long *arg_1,
[in][range(0,268435456)] long arg_2,
[in][size_is(arg_2)]/*[range(0,268435456)]*/ char arg_3[],
[out]/* simple_ref */hyper *arg_4);

error_status_t Proc19_BthServEirUpdateRecord(
[in][context_handle] void* arg_0,
[out]/* simple_ref */long *arg_1,
[in][range(0,268435456)] long arg_2,
[in][size_is(arg_2)]/*[range(0,268435456)]*/ char arg_3[],
[in]hyper arg_4);

error_status_t Proc20_BthServEirRemoveRecord(
[in][context_handle] void* arg_0,
[out]/* simple_ref */long *arg_1,
[in]hyper arg_2);

error_status_t Proc21_BthServTestRegisterAuthenticationEvent(
[in][context_handle] void* arg_0,
[out]/* simple_ref */long *arg_1,
[in]/* simple_ref */hyper *arg_2,
[in]hyper arg_3);
}

