knowledgeDict = {
                    'print spooler':['localspl.dll'],
                    'print workflow service': ['PrintWorkflowService.dll'],
                    'print':['localspl.dll','printconfig.dll','printui.exe'],
                    'link':['shell32.dll','windows.storage.dll,','structuredquery.dll'],
                    'lnk': ['shell32.dll','windows.storage.dll,','structuredquery.dll'],
                    'dhcp':['dhcpcmonitor.dll','dhcpcore.dll','dhcpcore6.dll','dhcpcsvc.dll','dhcpcsvc6.dll','dhcpsapi.dll'],
                    'chakra scripting engine':['chakra.dll', 'chakradiag.dll', 'chakrathunk.dll'],#edge scripting engine that replaced jscript9.dll
                    'chakracore scripting engine':['chakra.dll', 'chakradiag.dll', 'chakrathunk.dll'],#edge scripting engine that replaced jscript9.dll
                    'chakra':['chakra.dll', 'chakradiag.dll', 'chakrathunk.dll'], #edge scripting engine that replaced jscript9.dll
                    'scripting engine':['iexplore.exe'], # should add to this list. for example:https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2020-0674 https://www.exploit-db.com/exploits/48806
                    'excel':['excel.exe'],
                    'word':['winword.exe'],
                    'network connections service':['ncbservice.dll','ncpa.cpl','ncsi.dll','ncuprov.dll','netman.dll','netshell.dll'],
                    'error reporting manager':['wermgr.exe'],
                    'error reporting':['wer.dll','wersvc.dll','werfault.dll','werdiagcontroller.dll','werfault.exe','werfaultsecure.exe','werconcpl.dll','wermgr.exe','wercplsupport.dll'],
                    'kernelstream':['portcls.sys','stream.sys','ks.sys'], #maybe according to https://docs.microsoft.com/en-us/windows-hardware/drivers/stream/kernel-streaming
                    'installer':['msiexec.exe','msi.dll','msihnd.dll','msimsg.dll'], # see for example https://github.com/padovah4ck/CVE-2020-0683/blob/master/MSI_EoP_New.pdf
                    'update orchestrator service':['usosvc.dll'], #https://github.com/irsl/CVE-2020-1313
                    'kernel':['win32k.sys','ntoskrnl.exe','kernelbase.dll'], # ntos example: https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2018-8611 , CVE-2020-0821
                    'kernel-mode driver':['win32k.sys'],
                    'win32k component':['win32k.sys'],
                    'user-mode power service':['umpo.dll'], # https://0xeb-bp.com/blog/2020/05/12/cve-2020-1015-analysis.html
                    'sql server reporting services':['reportingserviceswebserver.dll'], #cve-2020-0618
                    'server message block 1.0':['srv.sys','srv2.sys','mrxsmb10.sys','mrxsmb20.sys'], #https://airbus-cyber-security.com/diving-into-the-smblost-vulnerability-cve-2020-1301/
                    'server message block 2.0':['srv2.sys','smbwmiv2.dll','mrxsmb10.sys','mrxsmb20.sys'],
                    'implementations of server message block 2.0 and 3.0':['srv.sys','srv2.sys','smbwmiv2.dll'],
                    'smb server':['smiengine.dll','srv2.sys','smbwmiv2.dll'],
                    'jet database engine':['msaccess.exe','msjet40.dll','msexcl40.dll','msrd2x40.dll','msrd3x40.dll','msexch40.dll','msexcl40.dll','msltus40.dll'],
                    'office access connectivity engine':['msaccess.exe','msjet40.dll','msexcl40.dll','msrd2x40.dll','mmsexcl40.dll','srd3x40.dll'],#https://www.fortiguard.com/zeroday/FG-VD-19-018
                    'sharepoint':['microsoft.sharepoint.dll','microsoft.sharepoint.portal.dll'],
                    'remote desktop services':['termdd.sys','rdpwd.sys','mstscax.dll'], #https://blog.rapid7.com/2020/02/04/doublepulsar-rce-2-an-rdp-story/
                    'common log file system':['clfs.sys'],
                    'graphics device interface plus':['gdiplus.dll'],
                    'graphics device interface':['gdiplus.dll','gdi32.dll','gdi32full.dll'], #CVE-2019-0618
                    'gdi component':['gdiplus.dll','gdi32.dll','gdi32full.dll','msimg32.dll'],
                    'gdi+ component':['gdiplus.dll','gdi32.dll','gdi32full.dll','msimg32.dll'],
                    'graphics components':['mf3216.dll','gdiplus.dll','gdi32.dll','gdi32full.dll'],
                    'graphics component':['mf3216.dll','gdiplus.dll','gdi32.dll','gdi32full.dll'], #example out of other components: https://www.zerodayinitiative.com/advisories/ZDI-20-876/
                    'diagnostics hub standard collector or visual studio standard collector':['diagnosticshub.standardcollector.runtime.dll'], # https://github.com/atredispartners/CVE-2018-0952-SystemCollector/blob/master/README.md
                    'diagnostics hub standard collector':['diagnosticshub.standardcollector.runtime.dll'], # https://github.com/atredispartners/CVE-2018-0952-SystemCollector/blob/master/README.md
                    'work folder service':['workfolders.exe','workfolderscontrol.dll','workfoldersshell.dll','workfolderssvc.dll'],
                    'remote desktop protocol':['rdpcorets.dll','rdpudd.dll','rdpvideominiport.sys','rdpcore.dll','rdp4vs.dll','rdpclip.exe','mstscax.dll'],
                    'remote desktop client':['rdvidcrl.dll','rdpcorets.dll','rdpudd.dll','rdpvideominiport.sys','rdpcore.dll','rdp4vs.dll','rdpclip.exe','lscshostpolicy.dll','tsrpc.dll','tsvmhasvc.dll','tsv_migplugin.dll'],
                    'remote desktop protocol client':['rdvidcrl.dll','rdpcorets.dll','rdpudd.dll','rdpvideominiport.sys','rdpcore.dll','rdp4vs.dll','rdpclip.exe','lscshostpolicy.dll','tsrpc.dll','tsvmhasvc.dll','tsv_migplugin.dll','mstscax.dll'],
                    'remote desktop protocol server':['rdvidcrl.dll','rdpcorets.dll','rdpudd.dll','rdpvideominiport.sys','rdpcore.dll','rdp4vs.dll','rdpclip.exe','mstscax.dll'],
                    'terminal services component':['termsrv.dll'],
                    'rdp gateway server':['rdwebserviceasp.dll','tsmf.dll'],
                    'font library':['fontsub.dll','fntcache.dll'],
                    'cryptographic catalogs':['cryptcatsvc.dll'],
                    'cryptographic':['ncrypt.dll','bcrypt.dll','ncryptsslp.dll','bcryptprimitives.dll','cryptcatsvc.dll'],
                    'rsop application':['rsopprov.exe'],
                    'hyper-v remotefx vgpu':['remotefxvgpudisablement.exe'], #https://support.microsoft.com/en-us/help/4570006/update-to-disable-and-remove-the-remotefx-vgpu-component
                    'address book':['wab32.dll','wab32res.dll','wabimp.dll','wabsyncprovider.dll'],#CVE-2020-1410
                    'lsass':['lsass.exe','netlogon.dll','msv1_0.dll','kerberos.dll','wdigest.dll'],#https://www.preempt.com/blog/security-advisory-integer-overflow-in-active-directory-cve-2020-1267/
                    'media audio codec':['wmadmod.dll'],
                    'media audio decoder':['wmadmod.dll'],
                    'media video decoder':['wmvdecod.dll'],
                    'directwrite':['dwrite.dll'],#https://blog.tetrane.com/2019/11/17/Analyzing_an_Out_of_Bounds_read_in_a_TTF_font_file.html
                    'ntfs':['ntfs.sys'],
                    'rsop service application':['rsopprov.exe'],
                    'background intelligent transfer service':['bitsigd.dll','bitsprx2.dll','bitsprx3.dll','bitsprx4.dll','bitsprx5.dll','bitsprx6.dll','bitsprx7.dll','qmgr.dll','qmgrprxy.dll','bitsmig.dll',' bitssrv.dll'],
                    'an ole automation component':['ole32.dll','oleaut32.dll'],
                    'ole automation':['ole32.dll','oleaut32.dll','oleprn.dll'],
                    'netbios over tcp':['netbt.sys'],
                    'netbt session services':['netbt.sys'],
                    'network driver interface specification':['ndiswan.sys','ndis.sys'],
                    'ndis':['ndiswan.sys','ndis.sys'],
                    'cryptography next generation':['cng.sys'],
                    'font driver host':['fontsub.dll'],
                    'credential enrollment manager':['windows.security.credentials.ui.credentialpicker.dll'],
                    'appx deployment extensions':['appxdeploymentclient.dll','appxalluserstore.dll','appxdeploymentclient.dll','appxdeploymentextensions.dll','appxdeploymentserver.dll','appxupgrademigrationplugin.dll','appxalluserstore.dll'],
                    'deployment services tftp server':['wdstftp.dll'],
                    'xml core services msxml parser':['msxml3.dll','msxml3r.dll','msxml6.dll','msxml6r.dll'],
                    'xml core services':['msxml3.dll','msxml3r.dll','msxml6.dll','msxml6r.dll'],
                    'tcp/ip stack':['tcpip.sys'],
                    'hyper-v network switch on a host server':['vmsif.dll','vmsntfy.dll','vmswitch.sys','vmsnetsetupplugin.dll'],
                    'push notification service':['wpncore.dll'],
                    'store install service':['windows.storage.applicationdata.dll'],
                    'printer service':['printfilterpipelineprxy.dll','printfilterpipelinesvc.exe'],
                    'credential enrollment manager service':['windows.security.credentials.ui.credentialpicker.dll'],
                    'ancillary function driver for winsock':['afd.sys'],
                    'file server resource management service':['fsrmmsvr.exe','srmsvc.dll'],
                    'credential security support provider protocol':['credssp.dll'],
                    'snmp service':['wsnmp32.dll'],
                    'wordpad':['wordpad.exe','wordpadfilter.dll'],
                    'powershell':['microsoft.powershell.commands.utility.dll','microsoft.powershell.graphicalhost.dll'],
                    'remotefx virtual gpu miniport driver':['rfxvmt.sys'],
                    'pdf library':['windows.data.pdf.dll'],
                    'image acquisition':['wiaaut.dll','wiadss.dll','wiafbdrv.dll','wiarpc.dll','wiaservc.dll','wiatrace.dll','wiarpc.dll','wiaservc.dll','wiatrace.dll'],
                    'search indexer':['mssitlb.dll','searchprotocolhost.exe','tquery.dll','searchfilterhost.exe','wsearchmigplugin.dll','searchindexer.exe','msscntrs.dll','msshooks.dll','mssprxy.dll','mssphtb.dll','mssph.dll','mssvp.dll','mssrch.dll'],
                    'imaging library':['wimserv.exe','wimmount.sys','wimgapi.dll','wimprovider.dll'],
                    'network file system':['msnfsflt.sys','nfssvc.exe','nfssvr.sys'],
                    'common log file system driver':['clfs.sys'],
                    'port class library':['portcls.sys'],
                    'upnp':['umpnpmgr.dll','upnpcont.exe','upnphost.dll'],
                    'adobe font manager library':['atmfd.dll'], #https://www.kaspersky.com/blog/windows-adobe-type-manager-vulnerability/34395/
                    'function discovery service':['fdwsd.dll'],
                    'local security authority subsystem service':['lsass.exe','netlogon.dll','msv1_0.dll','kerberos.dll','wdigest.dll'],
                    'wlan service':['wlanapi.dll','wlanhlp.dll','wlanmsm.dll','wlansec.dll','wlansvc.dll','wlansvcpal.dll'],
                    'core shell com server registrar':['CoreShellExtFramework.dll'],#cve-2019-1184 - https://www.zerodayinitiative.com/blog/2019/12/19/privilege-escalation-via-the-core-shell-com-registrar-object
                    'digital media receiver':['dmrserver.dll','dmrserver.exe'],
                }
serviceDict = {
    'distributed link tracking client': {'shortName': 'trkwks', 'file': 'trkwks.dll'},
    'themes': {'shortName': 'themes', 'file': 'themeservice.dll'},
    'font cache': {'shortName': 'fontcache', 'file': 'fntcache.dll'},
    'distributed transaction coordinator': {'shortName': 'msdtc', 'file': '@comres.dll'},
    'wmi performance adapter': {'shortName': 'wmiapsrv', 'file': 'wbem\\wmiapsrv.exe'},
    'remote procedure call (rpc)': {'shortName': 'rpcss', 'file': '@combase.dll'},
    'management instrumentation': {'shortName': 'winmgmt', 'file': 'wbem\\wmisvc.dll'},
    'display enhancement': {'shortName': 'displayenhancementservice', 'file': 'microsoft.graphics.display.displayenhancementservice.dll'},
    'background intelligent transfer': {'shortName': 'bits', 'file': 'qmgr.dll'},
    'microsoft account sign-in assistant': {'shortName': 'wlidsvc', 'file': 'wlidsvc.dll'},
    'state repository': {'shortName': 'staterepository', 'file': 'windows.staterepository.dll'},
    'program compatibility assistant': {'shortName': 'pcasvc', 'file': 'pcasvc.dll'},
    'push notifications user service_3852f1': {'shortName': 'wpnuserservice_3852f1', 'file': 'wpnuserservice.dll'},
    'network location awareness': {'shortName': 'nlasvc', 'file': 'nlasvc.dll'},
    'background tasks infrastructure': {'shortName': 'brokerinfrastructure', 'file': 'bisrv.dll'},
    'hyper-v host compute': {'shortName': 'vmcompute', 'file': 'vmcompute.exe'},
    'data sharing': {'shortName': 'dssvc', 'file': 'dssvc.dll'},
    'sync host_3852f1': {'shortName': 'onesyncsvc_3852f1', 'file': 'aphostres.dll'},
    'time broker': {'shortName': 'timebrokersvc', 'file': 'timebrokerserver.dll'},
    'touch keyboard and handwriting panel': {'shortName': 'tabletinputservice', 'file': 'tabsvc.dll'},
    'secure socket tunneling protocol': {'shortName': 'sstpsvc', 'file': 'sstpsvc.dll'},
    'server': {'shortName': 'lanmanserver', 'file': 'srvsvc.dll'},
    'capability access manager': {'shortName': 'camsvc', 'file': 'capabilityaccessmanager.dll'},
    'search': {'shortName': 'wsearch', 'file': 'searchindexer.exe'},
    'defender firewall': {'shortName': 'mpssvc', 'file': 'firewallapi.dll'},
    'display policy': {'shortName': 'dispbrokerdesktopsvc', 'file': 'dispbroker.desktop.dll'},
    'device association': {'shortName': 'deviceassociationservice', 'file': 'das.dll'},
    'sysmain': {'shortName': 'sysmain', 'file': 'sysmain.dll'},
    'user manager': {'shortName': 'usermanager', 'file': 'usermgr.dll'},
    'bluetooth audio gateway': {'shortName': 'btagservice', 'file': 'btagservice.dll'},
    'network store interface': {'shortName': 'nsi', 'file': 'nsisvc.dll'},
    'bluetooth support': {'shortName': 'bthserv', 'file': 'bthserv.dll'},
    'com+ system application': {'shortName': 'comsysapp', 'file': '@comres.dll'},
    'diagnostic system host': {'shortName': 'wdisystemhost', 'file': 'wdi.dll'},
    'host network': {'shortName': 'hns', 'file': 'hostnetsvc.dll'},
    'biometric': {'shortName': 'wbiosrvc', 'file': 'wbiosrvc.dll'},
    'avctp': {'shortName': 'bthavctpsvc', 'file': 'bthavctpsvc.dll'},
    'user profile': {'shortName': 'profsvc', 'file': 'profsvc.dll'},
    'power': {'shortName': 'power', 'file': 'umpo.dll'},
    'security': {'shortName': 'securityhealthservice', 'file': 'securityhealthagent.dll'},
    'audio': {'shortName': 'audiosrv', 'file': 'audiosrv.dll'},
    'cryptographic': {'shortName': 'cryptsvc', 'file': 'cryptsvc.dll'},
    'event log': {'shortName': 'eventlog', 'file': 'wevtsvc.dll'},
    'dns client': {'shortName': 'dnscache', 'file': 'dnsapi.dll'},
    'dcom server process launcher': {'shortName': 'dcomlaunch', 'file': '@combase.dll'},
    'base filtering engine': {'shortName': 'bfe', 'file': 'bfe.dll'},
    'connected devices platform': {'shortName': 'cdpsvc', 'file': 'cdpsvc.dll'},
    'connected devices platform user': {'shortName': 'cdpusersvc_3852f1', 'file': 'cdpusersvc.dll'},
    'ip helper': {'shortName': 'iphlpsvc', 'file': 'iphlpsvc.dll'},
    'system event notification': {'shortName': 'sens', 'file': 'sens.dll'},
    'hv host': {'shortName': 'hvhost', 'file': 'hvhostsvc.dll'},
    'network virtualization': {'shortName': 'nvagent', 'file': 'nvagent.dll'},
    'devquery background discovery broker': {'shortName': 'devquerybroker', 'file': 'devquerybroker.dll'},
    'system events broker': {'shortName': 'systemeventsbroker', 'file': 'systemeventsbrokerserver.dll'},
    'contact data_3852f1': {'shortName': 'pimindexmaintenancesvc_3852f1', 'file': 'userdataaccessres.dll'},
    'container manager': {'shortName': 'cmservice', 'file': 'cmservice.dll'},
    'diagnostic': {'shortName': 'wdiservicehost', 'file': 'wdi.dll'},
    'remote desktop configuration': {'shortName': 'sessionenv', 'file': 'sessenv.dll'},
    'system guard runtime monitor broker': {'shortName': 'sgrmbroker', 'file': 'sgrmbroker.exe'},
    'microsoft store install': {'shortName': 'installservice', 'file': 'installservice.dll'},
    'license manager': {'shortName': 'licensemanager', 'file': 'licensemanagersvc.dll'},
    'task scheduler': {'shortName': 'schedule', 'file': 'schedsvc.dll'},
    'update orchestrator': {'shortName': 'usosvc', 'file': 'usosvc.dll'},
    'certificate propagation': {'shortName': 'certpropsvc', 'file': 'certprop.dll'},
    'client license service (clipsvc)': {'shortName': 'clipsvc', 'file': 'clipsvc.dll'},
    'network connection broker': {'shortName': 'ncbservice', 'file': 'ncbservice.dll'},
    'local session manager': {'shortName': 'lsm', 'file': 'lsm.dll'},
    'audio endpoint builder': {'shortName': 'audioendpointbuilder', 'file': 'audioendpointbuilder.dll'},
    'presentation foundation font cache 3.0.0.0': {'shortName': 'fontcache3.0.0.0', 'file': 'presentationhost.exe'},
    'com+ event system': {'shortName': 'eventsystem', 'file': '@comres.dll'},
    'workstation': {'shortName': 'lanmanworkstation', 'file': 'wkssvc.dll'},
    'print spooler': {'shortName': 'spooler', 'file': 'spoolsv.exe'},
    'application information': {'shortName': 'appinfo', 'file': 'appinfo.dll'},
    'winhttp web proxy auto-discovery': {'shortName': 'winhttpautoproxysvc', 'file': 'winhttp.dll'},
    'remote desktop services': {'shortName': 'termservice', 'file': 'termsrv.dll'},
    'shell hardware detection': {'shortName': 'shellhwdetection', 'file': 'shsvcs.dll'},
    'connection manager': {'shortName': 'wcmsvc', 'file': 'wcmsvc.dll'},
    'connected user experiences and telemetry': {'shortName': 'diagtrack', 'file': 'diagtrack.dll'},
    'radio management': {'shortName': 'rmsvc', 'file': 'rmapi.dll'},
    'plug and play': {'shortName': 'plugplay', 'file': 'umpnpmgr.dll'},
    'user data storage_3852f1': {'shortName': 'unistoresvc_3852f1', 'file': 'userdataaccessres.dll'},
    'diagnostic policy': {'shortName': 'dps', 'file': 'dps.dll'},
    'user data access_3852f1': {'shortName': 'userdatasvc_3852f1', 'file': 'userdataaccessres.dll'},
    'data usage': {'shortName': 'dusmsvc', 'file': 'dusmsvc.dll'},
    'credential manager': {'shortName': 'vaultsvc', 'file': 'vaultsvc.dll'},
    'bluetooth user support': {'shortName': 'bluetoothuserservice_3852f1', 'file': 'microsoft.bluetooth.userservice.dll'},
    'telephony': {'shortName': 'tapisrv', 'file': 'tapisrv.dll'},
    'security accounts manager': {'shortName': 'samss', 'file': 'samsrv.dll'},
    'clipboard user service_3852f1': {'shortName': 'cbdhsvc_3852f1', 'file': 'cbdhsvc.dll'},
    'human interface device': {'shortName': 'hidserv', 'file': 'hidserv.dll'},
    'security center': {'shortName': 'wscsvc', 'file': 'wscsvc.dll'},
    'coremessaging': {'shortName': 'coremessagingregistrar', 'file': 'coremessaging.dll'},
    'push notifications system': {'shortName': 'wpnservice', 'file': 'wpnservice.dll'},
    'image acquisition (wia)': {'shortName': 'stisvc', 'file': 'wiaservc.dll'},
    'remote access connection manager': {'shortName': 'rasman', 'file': 'rasmans.dll'},
    'cng key isolation': {'shortName': 'keyiso', 'file': '@keyiso.dll'},
    'network list': {'shortName': 'netprofm', 'file': 'netprofmsvc.dll'},
    'rpc endpoint mapper': {'shortName': 'rpceptmapper', 'file': 'rpcepmap.dll'},
    'wlan autoconfig': {'shortName': 'wlansvc', 'file': 'wlansvc.dll'},
    'web account manager': {'shortName': 'tokenbroker', 'file': 'tokenbroker.dll'},
    'remote desktop services usermode port redirector': {'shortName': 'umrdpservice', 'file': 'umrdp.dll'},
    'storage': {'shortName': 'storsvc', 'file': 'storsvc.dll'},
    'dhcp client': {'shortName': 'dhcp', 'file': 'dhcpcore.dll'},
    'bitlocker drive encryption': {'shortName': 'bdesvc', 'file': 'bdesvc.dll'},
    'ssdp discovery': {'shortName': 'ssdpsrv', 'file': 'ssdpsrv.dll'},
    'tcp/ip netbios helper': {'shortName': 'lmhosts', 'file': 'lmhsvc.dll'},
    }
cweIdDict = {
	'284':'PillarImproper Access Control',
	'1220':'BaseInsufficient Granularity of Access Control',
	'1222':'VariantInsufficient Granularity of Address Regions Protected by Register Locks',
	'1224':'BaseImproper Restriction of Write-Once Bit Fields',
	'1231':'BaseImproper Implementation of Lock Protection Registers',
	'1242':'BaseInclusion of Undocumented Features or Chicken Bits',
	'1252':'BaseCPU Hardware Not Configured to Support Exclusivity of Write and Execute Operations',
	'1256':'BaseHardware Features Enable Physical Attacks from Software',
	'1257':'BaseImproper Access Control Applied to Mirrored or Aliased Memory Regions',
	'1259':'BaseImproper Restriction of Security Token Assignment',
	'1260':'BaseImproper Handling of Overlap Between Protected Memory Ranges',
	'1262':'BaseRegister Interface Allows Software Access to Sensitive Data or Security Settings',
	'1263':'ClassImproper Physical Access Control',
	'1267':'BasePolicy Uses Obsolete Encoding',
	'1268':'BasePolicy Privileges are not Assigned Consistently Between Control and Data Agents',
	'1270':'BaseGeneration of Incorrect Security Tokens',
	'1274':'BaseInsufficient Protections on the Volatile Memory Containing Boot Code',
	'1275':'VariantSensitive Cookie with Improper SameSite Attribute',
	'1276':'BaseHardware Child Block Incorrectly Connected to Parent System',
	'1280':'BaseAccess Control Check Implemented After Asset is Accessed',
	'1283':'BaseMutable Attestation or Measurement Reporting Data',
	'1290':'BaseIncorrect Decoding of Security Identifiers',
	'1292':'BaseIncorrect Conversion of Security Identifiers',
	'1294':'ClassInsecure Security Identifier Mechanism',
	'1302':'BaseMissing Security Identifier',
	'1296':'BaseIncorrect Chaining or Granularity of Debug Components',
	'1304':'BaseImproperly Preserved Integrity of Hardware Configuration State During a Power Save/Restore Operation',
	'269':'ClassImproper Privilege Management',
	'250':'BaseExecution with Unnecessary Privileges',
	'266':'BaseIncorrect Privilege Assignment',
	'1022':'VariantUse of Web Link to Untrusted Target with window.opener Access',
	'520':'Variant.NET Misconfiguration: Use of Impersonation',
	'556':'VariantASP.NET Misconfiguration: Use of Identity Impersonation',
	'9':'VariantJ2EE Misconfiguration: Weak Access Permissions for EJB Methods',
	'267':'BasePrivilege Defined With Unsafe Actions',
	'623':'VariantUnsafe ActiveX Control Marked Safe For Scripting',
	'268':'BasePrivilege Chaining',
	'270':'BasePrivilege Context Switching Error',
	'271':'ClassPrivilege Dropping / Lowering Errors',
	'272':'BaseLeast Privilege Violation',
	'273':'BaseImproper Check for Dropped Privileges',
	'274':'BaseImproper Handling of Insufficient Privileges',
	'648':'BaseIncorrect Use of Privileged APIs',
	'282':'ClassImproper Ownership Management',
	'283':'BaseUnverified Ownership',
	'708':'BaseIncorrect Ownership Assignment',
	'285':'ClassImproper Authorization',
	'1230':'BaseExposure of Sensitive Information Through Metadata',
	'202':'VariantExposure of Sensitive Information Through Data Queries',
	'612':'BaseImproper Authorization of Index Containing Sensitive Information',
	'1244':'BaseImproper Access to Sensitive Information Using Debug and Test Interfaces',
	'1297':'BaseUnprotected Confidential Information on Device is Accessible by OSAT Vendors',
	'552':'BaseFiles or Directories Accessible to External Parties',
	'219':'VariantStorage of File with Sensitive Data Under Web Root',
	'433':'VariantUnparsed Raw Web Content Delivery',
	'220':'VariantStorage of File With Sensitive Data Under FTP Root',
	'527':'VariantExposure of Version-Control Repository to an Unauthorized Control Sphere',
	'528':'VariantExposure of Core Dump File to an Unauthorized Control Sphere',
	'529':'VariantExposure of Access Control List Files to an Unauthorized Control Sphere',
	'530':'VariantExposure of Backup File to an Unauthorized Control Sphere',
	'539':'VariantUse of Persistent Cookies Containing Sensitive Information',
	'553':'VariantCommand Shell in Externally Accessible Directory',
	'732':'ClassIncorrect Permission Assignment for Critical Resource',
	'1004':'VariantSensitive Cookie Without "HttpOnly" Flag',
	'276':'BaseIncorrect Default Permissions',
	'277':'VariantInsecure Inherited Permissions',
	'278':'VariantInsecure Preserved Inherited Permissions',
	'279':'VariantIncorrect Execution-Assigned Permissions',
	'281':'BaseImproper Preservation of Permissions',
	'862':'ClassMissing Authorization',
	'425':'BaseDirect Request ',
	'638':'ClassNot Using Complete Mediation',
	'424':'ClassImproper Protection of Alternate Path',
	'425':'BaseDirect Request ',
	'939':'BaseImproper Authorization in Handler for Custom URL Scheme',
	'863':'ClassIncorrect Authorization',
	'1191':'BaseExposed Chip Debug and Test Interface With Insufficient or Missing Authorization',
	'551':'BaseIncorrect Behavior Order: Authorization Before Parsing and Canonicalization',
	'639':'BaseAuthorization Bypass Through User-Controlled Key',
	'566':'VariantAuthorization Bypass Through User-Controlled SQL Primary Key',
	'647':'VariantUse of Non-Canonical URL Paths for Authorization Decisions',
	'804':'BaseGuessable CAPTCHA',
	'926':'VariantImproper Export of Android Application Components',
	'927':'VariantUse of Implicit Intent for Sensitive Communication',
	'286':'ClassIncorrect User Management',
	'842':'BasePlacement of User into Incorrect Group',
	'287':'ClassImproper Authentication',
	'261':'BaseWeak Encoding for Password',
	'262':'BaseNot Using Password Aging',
	'263':'BasePassword Aging with Long Expiration',
	'288':'BaseAuthentication Bypass Using an Alternate Path or Channel',
	'1299':'BaseMissing Protection Mechanism for Alternate Hardware Interface',
	'425':'BaseDirect Request ',
	'289':'VariantAuthentication Bypass by Alternate Name',
	'290':'BaseAuthentication Bypass by Spoofing',
	'291':'VariantReliance on IP Address for Authentication',
	'293':'VariantUsing Referer Field for Authentication',
	'350':'VariantReliance on Reverse DNS Resolution for a Security-Critical Action',
	'294':'BaseAuthentication Bypass by Capture-replay',
	'295':'BaseImproper Certificate Validation',
	'296':"BaseImproper Following of a Certificate's Chain of Trust",
	'297':'VariantImproper Validation of Certificate with Host Mismatch',
	'298':'VariantImproper Validation of Certificate Expiration',
	'299':'BaseImproper Check for Certificate Revocation',
	'370':'VariantMissing Check for Certificate Revocation after Initial Check',
	'599':'VariantMissing Validation of OpenSSL Certificate',
	'301':'VariantReflection Attack in an Authentication Protocol',
	'302':'VariantAuthentication Bypass by Assumed-Immutable Data',
	'303':'BaseIncorrect Implementation of Authentication Algorithm',
	'304':'BaseMissing Critical Step in Authentication',
	'305':'BaseAuthentication Bypass by Primary Weakness',
	'306':'BaseMissing Authentication for Critical Function',
	'307':'BaseImproper Restriction of Excessive Authentication Attempts',
	'308':'BaseUse of Single-factor Authentication',
	'309':'BaseUse of Password System for Primary Authentication',
	'521':'BaseWeak Password Requirements',
	'258':'VariantEmpty Password in Configuration File',
	'522':'ClassInsufficiently Protected Credentials',
	'256':'BaseUnprotected Storage of Credentials',
	'257':'BaseStoring Passwords in a Recoverable Format',
	'260':'BasePassword in Configuration File',
	'13':'VariantASP.NET Misconfiguration: Password in Configuration File',
	'258':'VariantEmpty Password in Configuration File',
	'555':'VariantJ2EE Misconfiguration: Plaintext Password in Configuration File',
	'523':'BaseUnprotected Transport of Credentials',
	'549':'BaseMissing Password Field Masking',
	'593':'VariantAuthentication Bypass: OpenSSL CTX Object Modified after SSL Objects are Created',
	'603':'BaseUse of Client-Side Authentication',
	'620':'BaseUnverified Password Change',
	'640':'BaseWeak Password Recovery Mechanism for Forgotten Password',
	'645':'BaseOverly Restrictive Account Lockout Mechanism',
	'798':'BaseUse of Hard-coded Credentials',
	'259':'VariantUse of Hard-coded Password',
	'321':'VariantUse of Hard-coded Cryptographic Key',
	'804':'BaseGuessable CAPTCHA',
	'836':'BaseUse of Password Hash Instead of Password for Authentication',
	'346':'BaseOrigin Validation Error',
	'923':'ClassImproper Restriction of Communication Channel to Intended Endpoints',
	'291':'VariantReliance on IP Address for Authentication',
	'297':'VariantImproper Validation of Certificate with Host Mismatch',
	'300':'ClassChannel Accessible by Non-Endpoint',
	'322':'BaseKey Exchange without Entity Authentication',
	'350':'VariantReliance on Reverse DNS Resolution for a Security-Critical Action',
	'419':'BaseUnprotected Primary Channel',
	'420':'BaseUnprotected Alternate Channel',
	'1299':'BaseMissing Protection Mechanism for Alternate Hardware Interface',
	'421':'BaseRace Condition During Access to Alternate Channel',
	'422':'VariantUnprotected Windows Messaging Channel ',
	'925':'VariantImproper Verification of Intent by Broadcast Receiver',
	'940':'BaseImproper Verification of Source of a Communication Channel',
	'941':'BaseIncorrectly Specified Destination in a Communication Channel',
	'942':'VariantPermissive Cross-domain Policy with Untrusted Domains',
	'435':'PillarImproper Interaction Between Multiple Correctly-Behaving Entities',
	'1038':'ClassInsecure Automated Optimizations',
	'1037':'BaseProcessor Optimization Removal or Modification of Security-critical Code',
	'733':'BaseCompiler Optimization Removal or Modification of Security-critical Code',
	'14':'VariantCompiler Removal of Code to Clear Buffers',
	'188':'BaseReliance on Data/Memory Layout',
	'198':'BaseUse of Incorrect Byte Ordering',
	'436':'ClassInterpretation Conflict',
	'115':'BaseMisinterpretation of Input',
	'437':'BaseIncomplete Model of Endpoint Features',
	'444':'BaseInconsistent Interpretation of HTTP Requests ',
	'626':'VariantNull Byte Interaction Error ',
	'650':'VariantTrusting HTTP Permission Methods on the Server Side',
	'86':'VariantImproper Neutralization of Invalid Characters in Identifiers in Web Pages',
	'439':'BaseBehavioral Change in New Version or Environment',
	'664':'PillarImproper Control of a Resource Through its Lifetime',
	'118':'ClassIncorrect Access of Indexable Resource ',
	'119':'ClassImproper Restriction of Operations within the Bounds of a Memory Buffer',
	'120':'BaseBuffer Copy without Checking Size of Input ',
	'785':'VariantUse of Path Manipulation Function without Maximum-sized Buffer',
	'125':'BaseOut-of-bounds Read',
	'126':'VariantBuffer Over-read',
	'127':'VariantBuffer Under-read',
	'466':'BaseReturn of Pointer Value Outside of Expected Range',
	'680':'ChainInteger Overflow to Buffer Overflow',
	'786':'BaseAccess of Memory Location Before Start of Buffer',
	'124':'BaseBuffer Underwrite ',
	'127':'VariantBuffer Under-read',
	'787':'BaseOut-of-bounds Write',
	'121':'VariantStack-based Buffer Overflow',
	'122':'VariantHeap-based Buffer Overflow',
	'123':'BaseWrite-what-where Condition',
	'124':'BaseBuffer Underwrite ',
	'788':'BaseAccess of Memory Location After End of Buffer',
	'121':'VariantStack-based Buffer Overflow',
	'122':'VariantHeap-based Buffer Overflow',
	'126':'VariantBuffer Over-read',
	'805':'BaseBuffer Access with Incorrect Length Value',
	'806':'VariantBuffer Access Using Size of Source Buffer',
	'822':'BaseUntrusted Pointer Dereference',
	'823':'BaseUse of Out-of-range Pointer Offset',
	'824':'BaseAccess of Uninitialized Pointer',
	'825':'BaseExpired Pointer Dereference',
	'415':'VariantDouble Free',
	'416':'VariantUse After Free',
	'1229':'ClassCreation of Emergent Resource',
	'514':'ClassCovert Channel',
	'385':'BaseCovert Timing Channel',
	'515':'BaseCovert Storage Channel',
	'1246':'BaseImproper Write Handling in Limited-write Non-Volatile Memories',
	'1250':'BaseImproper Preservation of Consistency Between Independent Representations of Shared State',
	'1249':'BaseApplication-Level Admin Tool with Inconsistent View of Underlying Operating System',
	'1251':'BaseMirrored Regions with Different Values',
	'1277':'BaseFirmware Not Updateable',
	'221':'ClassInformation Loss or Omission',
	'222':'BaseTruncation of Security-relevant Information',
	'223':'BaseOmission of Security-relevant Information',
	'778':'BaseInsufficient Logging',
	'224':'BaseObscured Security-relevant Information by Alternate Name',
	'356':'BaseProduct UI does not Warn User of Unsafe Actions',
	'396':'BaseDeclaration of Catch for Generic Exception',
	'397':'BaseDeclaration of Throws for Generic Exception',
	'451':'ClassUser Interface ',
	'1007':'BaseInsufficient Visual Distinction of Homoglyphs Presented to User',
	'1021':'BaseImproper Restriction of Rendered UI Layers or Frames',
	'372':'BaseIncomplete Internal State Distinction',
	'400':'ClassUncontrolled Resource Consumption',
	'1235':'BaseIncorrect Use of Autoboxing and Unboxing for Performance Critical Operations',
	'770':'BaseAllocation of Resources Without Limits or Throttling',
	'774':'VariantAllocation of File Descriptors or Handles Without Limits or Throttling',
	'789':'VariantUncontrolled Memory Allocation',
	'771':'BaseMissing Reference to Active Allocated Resource',
	'773':'VariantMissing Reference to Active File Descriptor or Handle',
	'779':'BaseLogging of Excessive Data',
	'920':'BaseImproper Restriction of Power Consumption',
	'404':'ClassImproper Resource Shutdown or Release',
	'1266':'BaseImproper Scrubbing of Sensitive Data from Decommissioned Device',
	'262':'BaseNot Using Password Aging',
	'263':'BasePassword Aging with Long Expiration',
	'299':'BaseImproper Check for Certificate Revocation',
	'370':'VariantMissing Check for Certificate Revocation after Initial Check',
	'459':'BaseIncomplete Cleanup',
	'226':'BaseSensitive Information in Resource Not Removed Before Reuse',
	'1239':'VariantImproper Zeroization of Hardware Register',
	'1272':'BaseSensitive Information Uncleared Before Debug/Power State Transition',
	'1301':'BaseInsufficient or Incomplete Data Removal within Hardware Component',
	'244':'VariantImproper Clearing of Heap Memory Before Release ',
	'460':'BaseImproper Cleanup on Thrown Exception',
	'568':'Variantfinalize',
	'763':'BaseRelease of Invalid Pointer or Reference',
	'761':'VariantFree of Pointer not at Start of Buffer',
	'762':'VariantMismatched Memory Management Routines',
	'590':'VariantFree of Memory not on the Heap',
	'772':'BaseMissing Release of Resource after Effective Lifetime',
	'1091':'BaseUse of Object without Invoking Destructor Method',
	'401':'VariantMissing Release of Memory after Effective Lifetime',
	'775':'VariantMissing Release of File Descriptor or Handle after Effective Lifetime',
	'405':'ClassAsymmetric Resource Consumption ',
	'1050':'BaseExcessive Platform Resource Consumption within a Loop',
	'1072':'BaseData Resource Access without Use of Connection Pooling',
	'1073':'BaseNon-SQL Invokable Control Element with Excessive Number of Data Resource Accesses',
	'1084':'BaseInvokable Control Element with Excessive File or Data Access Operations',
	'1089':'BaseLarge Data Table with Excessive Number of Indices',
	'1094':'BaseExcessive Index Range Scan for a Data Resource',
	'1176':'ClassInefficient CPU Computation',
	'1042':'VariantStatic Member Data Element outside of a Singleton Class Element',
	'1046':'BaseCreation of Immutable Text Using String Concatenation',
	'1049':'BaseExcessive Data Query Operations in a Large Data Table',
	'1063':'BaseCreation of Class Instance within a Static Code Block',
	'1067':'BaseExcessive Execution of Sequential Searches of Data Resource',
	'406':'ClassInsufficient Control of Network Message Volume ',
	'407':'ClassInefficient Algorithmic Complexity',
	'408':'BaseIncorrect Behavior Order: Early Amplification',
	'409':'BaseImproper Handling of Highly Compressed Data ',
	'776':'BaseImproper Restriction of Recursive Entity References in DTDs ',
	'410':'BaseInsufficient Resource Pool',
	'471':'BaseModification of Assumed-Immutable Data ',
	'291':'VariantReliance on IP Address for Authentication',
	'472':'BaseExternal Control of Assumed-Immutable Web Parameter',
	'473':'VariantPHP External Variable Modification',
	'607':'VariantPublic Static Final Field References Mutable Object',
	'487':'BaseReliance on Package-level Scope',
	'488':'BaseExposure of Data Element to Wrong Session',
	'495':'VariantPrivate Data Structure Returned From A Public Method',
	'496':'VariantPublic Data Assigned to Private Array-Typed Field',
	'498':'VariantCloneable Class Containing Sensitive Information',
	'499':'VariantSerializable Class Containing Sensitive Data',
	'501':'BaseTrust Boundary Violation',
	'580':'Variantclone',
	'610':'ClassExternally Controlled Reference to a Resource in Another Sphere',
	'15':'BaseExternal Control of System or Configuration Setting',
	'384':'CompositeSession Fixation',
	'441':'ClassUnintended Proxy or Intermediary ',
	'1021':'BaseImproper Restriction of Rendered UI Layers or Frames',
	'918':'BaseServer-Side Request Forgery ',
	'470':'BaseUse of Externally-Controlled Input to Select Classes or Code ',
	'601':'BaseURL Redirection to Untrusted Site ',
	'611':'BaseImproper Restriction of XML External Entity Reference',
	'73':'BaseExternal Control of File Name or Path',
	'114':'ClassProcess Control',
	'662':'ClassImproper Synchronization',
	'1058':'BaseInvokable Control Element in Multi-Thread Context with non-Final Static Storable or Member Element',
	'663':'BaseUse of a Non-reentrant Function in a Concurrent Context',
	'479':'VariantSignal Handler Use of a Non-reentrant Function',
	'558':'VariantUse of getlogin',
	'667':'ClassImproper Locking',
	'1232':'BaseImproper Lock Behavior After Power State Transition',
	'1233':'BaseImproper Hardware Lock Protection for Security Sensitive Controls',
	'1234':'BaseHardware Internal or Debug Modes Allow Override of Locks',
	'412':'BaseUnrestricted Externally Accessible Lock',
	'413':'BaseImproper Resource Locking',
	'591':'VariantSensitive Data Storage in Improperly Locked Memory',
	'414':'BaseMissing Lock Check',
	'609':'BaseDouble-Checked Locking',
	'764':'BaseMultiple Locks of a Critical Resource',
	'765':'BaseMultiple Unlocks of a Critical Resource',
	'832':'BaseUnlock of a Resource that is not Locked',
	'833':'BaseDeadlock',
	'820':'BaseMissing Synchronization',
	'1096':'VariantSingleton Class Instance Creation without Proper Locking or Synchronization',
	'543':'VariantUse of Singleton Pattern Without Synchronization in a Multithreaded Context',
	'567':'BaseUnsynchronized Access to Shared Data in a Multithreaded Context',
	'821':'BaseIncorrect Synchronization',
	'1088':'BaseSynchronous Access of Remote Resource without Timeout',
	'1264':'BaseHardware Logic with Insecure De-Synchronization between Control and Data Channels',
	'572':'VariantCall to Thread run',
	'574':'VariantEJB Bad Practices: Use of Synchronization Primitives',
	'665':'ClassImproper Initialization',
	'1051':'BaseInitialization with Hard-Coded Network Resource Configuration Data',
	'1052':'BaseExcessive Use of Hard-Coded Literals in Initialization',
	'1188':'BaseInsecure Default Initialization of Resource',
	'453':'VariantInsecure Default Variable Initialization',
	'1221':'BaseIncorrect Register Defaults or Module Parameters',
	'1271':'ClassUnitialized Value on Reset for Registers Holding Security Settings',
	'1279':'BaseCryptographic Operations are run Before Supporting Units are Ready',
	'454':'BaseExternal Initialization of Trusted Variables or Data Stores',
	'455':'BaseNon-exit on Failed Initialization',
	'770':'BaseAllocation of Resources Without Limits or Throttling',
	'774':'VariantAllocation of File Descriptors or Handles Without Limits or Throttling',
	'789':'VariantUncontrolled Memory Allocation',
	'908':'BaseUse of Uninitialized Resource',
	'457':'VariantUse of Uninitialized Variable',
	'909':'BaseMissing Initialization of Resource',
	'456':'VariantMissing Initialization of a Variable',
	'666':'ClassOperation on Resource in Wrong Phase of Lifetime',
	'415':'VariantDouble Free',
	'593':'VariantAuthentication Bypass: OpenSSL CTX Object Modified after SSL Objects are Created',
	'605':'BaseMultiple Binds to the Same Port',
	'672':'ClassOperation on a Resource after Expiration or Release',
	'298':'VariantImproper Validation of Certificate Expiration',
	'324':'BaseUse of a Key Past its Expiration Date',
	'613':'BaseInsufficient Session Expiration',
	'825':'BaseExpired Pointer Dereference',
	'415':'VariantDouble Free',
	'416':'VariantUse After Free',
	'910':'BaseUse of Expired File Descriptor',
	'826':'BasePremature Release of Resource During Expected Lifetime',
	'668':'ClassExposure of Resource to Wrong Sphere',
	'1189':'BaseImproper Isolation of Shared Resources on System-on-a-Chip ',
	'1303':'BaseNon-Transparent Sharing of Microarchitectural Resources',
	'1282':'BaseAssumed-Immutable Data is Stored in Writable Memory',
	'134':'BaseUse of Externally-Controlled Format String',
	'200':'ClassExposure of Sensitive Information to an Unauthorized Actor',
	'1243':'BaseSensitive Non-Volatile Information Not Protected During Debug',
	'1258':'BaseExposure of Sensitive System Information Due to Uncleared Debug Information',
	'1273':'BaseDevice Unlock Credential Sharing',
	'1295':'BaseDebug Messages Revealing Unnecessary Information',
	'201':'BaseInsertion of Sensitive Information Into Sent Data',
	'598':'VariantUse of GET Request Method With Sensitive Query Strings',
	'203':'BaseObservable Differences in Behavior to Error Inputs',
	'1300':'BaseImproper Protection Against Physical Side Channels',
	'1303':'BaseNon-Transparent Sharing of Microarchitectural Resources',
	'204':'BaseObservable Response Discrepancy',
	'205':'BaseObservable Behavioral Discrepancy',
	'1255':'BaseComparison Logic is Vulnerable to Power Side-Channel Attacks',
	'206':'VariantObservable Internal Behavioral Discrepancy',
	'207':'VariantObservable Behavioral Discrepancy With Equivalent Products',
	'208':'BaseObservable Timing Discrepancy',
	'1254':'BaseIncorrect Comparison Logic Granularity',
	'209':'BaseGeneration of Error Message Containing Sensitive Information',
	'210':'BaseSelf-generated Error Message Containing Sensitive Information',
	'211':'BaseExternally-Generated Error Message Containing Sensitive Information',
	'535':'VariantExposure of Information Through Shell Error Message',
	'536':'VariantServlet Runtime Error Message Containing Sensitive Information',
	'537':'VariantJava Runtime Error Message Containing Sensitive Information',
	'550':'VariantServer-generated Error Message Containing Sensitive Information',
	'213':'BaseExposure of Sensitive Information Due to Incompatible Policies',
	'215':'BaseInsertion of Sensitive Information Into Debugging Code',
	'359':'BaseExposure of Private Personal Information to an Unauthorized Actor',
	'497':'BaseExposure of Sensitive System Information to an Unauthorized Control Sphere',
	'214':'BaseInvocation of Process Using Visible Sensitive Information',
	'526':'VariantExposure of Sensitive Information Through Environmental Variables',
	'548':'VariantExposure of Information Through Directory Listing',
	'538':'BaseInsertion of Sensitive Information into Externally-Accessible File or Directory',
	'532':'BaseInsertion of Sensitive Information into Log File',
	'540':'BaseInclusion of Sensitive Information in Source Code',
	'531':'VariantInclusion of Sensitive Information in Test Code',
	'541':'VariantInclusion of Sensitive Information in an Include File',
	'615':'VariantInclusion of Sensitive Information in Source Code Comments',
	'651':'VariantExposure of WSDL File Containing Sensitive Information',
	'22':'BaseImproper Limitation of a Pathname to a Restricted Directory ',
	'23':'BaseRelative Path Traversal',
	'24':"VariantPath Traversal: '../filedir'",
	'25':"VariantPath Traversal: '/../filedir'",
	'26':"VariantPath Traversal: '/dir/../filename'",
	'27':"VariantPath Traversal: 'dir/../../filename'",
	'28':"VariantPath Traversal: '..\filedir'",
	'29':"VariantPath Traversal: '\..\filename'",
	'30':"VariantPath Traversal: '\dir\..\filename'",
	'31':"VariantPath Traversal: 'dir\..\..\filename'",
	'32':"VariantPath Traversal: '...' ",
	'33':"VariantPath Traversal: '....' ",
	'34':"VariantPath Traversal: '....//'",
	'35':"VariantPath Traversal: '.../...//'",
	'36':'BaseAbsolute Path Traversal',
	'37':"VariantPath Traversal: '/absolute/pathname/here'",
	'38':"VariantPath Traversal: '\absolute\pathname\here'",
	'39':"VariantPath Traversal: 'C:dirname'",
	'40':"VariantPath Traversal: '\\UNC\share\name\' ",
	'374':'BasePassing Mutable Objects to an Untrusted Method',
	'375':'BaseReturning a Mutable Object to an Untrusted Caller',
	'377':'ClassInsecure Temporary File',
	'378':'BaseCreation of Temporary File With Insecure Permissions',
	'379':'BaseCreation of Temporary File in Directory with Insecure Permissions',
	'402':'ClassTransmission of Private Resources into a New Sphere ',
	'403':'BaseExposure of File Descriptor to Unintended Control Sphere ',
	'619':'BaseDangling Database Cursor ',
	'427':'BaseUncontrolled Search Path Element',
	'428':'BaseUnquoted Search Path or Element',
	'491':'VariantPublic cloneable',
	'492':'VariantUse of Inner Class Containing Sensitive Data',
	'493':'VariantCritical Public Variable Without Final Modifier',
	'500':'VariantPublic Static Field Not Marked Final',
	'522':'ClassInsufficiently Protected Credentials',
	'256':'BaseUnprotected Storage of Credentials',
	'257':'BaseStoring Passwords in a Recoverable Format',
	'260':'BasePassword in Configuration File',
	'13':'VariantASP.NET Misconfiguration: Password in Configuration File',
	'258':'VariantEmpty Password in Configuration File',
	'555':'VariantJ2EE Misconfiguration: Plaintext Password in Configuration File',
	'523':'BaseUnprotected Transport of Credentials',
	'549':'BaseMissing Password Field Masking',
	'524':'BaseUse of Cache Containing Sensitive Information',
	'525':'VariantUse of Web Browser Cache Containing Sensitive Information',
	'552':'BaseFiles or Directories Accessible to External Parties',
	'219':'VariantStorage of File with Sensitive Data Under Web Root',
	'433':'VariantUnparsed Raw Web Content Delivery',
	'220':'VariantStorage of File With Sensitive Data Under FTP Root',
	'527':'VariantExposure of Version-Control Repository to an Unauthorized Control Sphere',
	'528':'VariantExposure of Core Dump File to an Unauthorized Control Sphere',
	'529':'VariantExposure of Access Control List Files to an Unauthorized Control Sphere',
	'530':'VariantExposure of Backup File to an Unauthorized Control Sphere',
	'539':'VariantUse of Persistent Cookies Containing Sensitive Information',
	'553':'VariantCommand Shell in Externally Accessible Directory',
	'582':'VariantArray Declared Public, Final, and Static',
	'583':'Variantfinalize',
	'608':'VariantStruts: Non-private Field in ActionForm Class',
	'642':'ClassExternal Control of Critical State Data',
	'15':'BaseExternal Control of System or Configuration Setting',
	'426':'BaseUntrusted Search Path',
	'472':'BaseExternal Control of Assumed-Immutable Web Parameter',
	'565':'BaseReliance on Cookies without Validation and Integrity Checking',
	'784':'VariantReliance on Cookies without Validation and Integrity Checking in a Security Decision',
	'73':'BaseExternal Control of File Name or Path',
	'114':'ClassProcess Control',
	'732':'ClassIncorrect Permission Assignment for Critical Resource',
	'1004':'VariantSensitive Cookie Without "HttpOnly" Flag',
	'276':'BaseIncorrect Default Permissions',
	'277':'VariantInsecure Inherited Permissions',
	'278':'VariantInsecure Preserved Inherited Permissions',
	'279':'VariantIncorrect Execution-Assigned Permissions',
	'281':'BaseImproper Preservation of Permissions',
	'767':'VariantAccess to Critical Private Variable via Public Method',
	'8':'VariantJ2EE Misconfiguration: Entity Bean Declared Remote',
	'927':'VariantUse of Implicit Intent for Sensitive Communication',
	'669':'ClassIncorrect Resource Transfer Between Spheres',
	'212':'BaseImproper Removal of Sensitive Information Before Storage or Transfer',
	'1258':'BaseExposure of Sensitive System Information Due to Uncleared Debug Information',
	'226':'BaseSensitive Information in Resource Not Removed Before Reuse',
	'1239':'VariantImproper Zeroization of Hardware Register',
	'1272':'BaseSensitive Information Uncleared Before Debug/Power State Transition',
	'1301':'BaseInsufficient or Incomplete Data Removal within Hardware Component',
	'244':'VariantImproper Clearing of Heap Memory Before Release ',
	'243':'VariantCreation of chroot Jail Without Changing Working Directory',
	'434':'BaseUnrestricted Upload of File with Dangerous Type',
	'494':'BaseDownload of Code Without Integrity Check',
	'602':'BaseClient-Side Enforcement of Server-Side Security',
	'565':'BaseReliance on Cookies without Validation and Integrity Checking',
	'784':'VariantReliance on Cookies without Validation and Integrity Checking in a Security Decision',
	'603':'BaseUse of Client-Side Authentication',
	'829':'BaseInclusion of Functionality from Untrusted Control Sphere',
	'827':'VariantImproper Control of Document Type Definition',
	'830':'VariantInclusion of Web Functionality from an Untrusted Source',
	'98':'VariantImproper Control of Filename for Include/Require Statement in PHP Program ',
	'673':'ClassExternal Influence of Sphere Definition',
	'426':'BaseUntrusted Search Path',
	'704':'ClassIncorrect Type Conversion or Cast',
	'588':'VariantAttempt to Access Child of a Non-structure Pointer',
	'681':'BaseIncorrect Conversion between Numeric Types',
	'1255':'BaseComparison Logic is Vulnerable to Power Side-Channel Attacks',
	'192':'VariantInteger Coercion Error',
	'194':'VariantUnexpected Sign Extension',
	'195':'VariantSigned to Unsigned Conversion Error',
	'196':'VariantUnsigned to Signed Conversion Error',
	'197':'BaseNumeric Truncation Error',
	'843':'BaseAccess of Resource Using Incompatible Type ',
	'706':'ClassUse of Incorrectly-Resolved Name or Reference',
	'178':'BaseImproper Handling of Case Sensitivity',
	'22':'BaseImproper Limitation of a Pathname to a Restricted Directory ',
	'23':'BaseRelative Path Traversal',
	'24':"VariantPath Traversal: '../filedir'",
	'25':"VariantPath Traversal: '/../filedir'",
	'26':"VariantPath Traversal: '/dir/../filename'",
	'27':"VariantPath Traversal: 'dir/../../filename'",
	'28':"VariantPath Traversal: '..\filedir'",
	'29':"VariantPath Traversal: '\..\filename'",
	'30':"VariantPath Traversal: '\dir\..\filename'",
	'31':"VariantPath Traversal: 'dir\..\..\filename'",
	'32':"VariantPath Traversal: '...' ",
	'33':"VariantPath Traversal: '....' ",
	'34':"VariantPath Traversal: '....//'",
	'35':"VariantPath Traversal: '.../...//'",
	'36':'BaseAbsolute Path Traversal',
	'37':"VariantPath Traversal: '/absolute/pathname/here'",
	'38':"VariantPath Traversal: '\absolute\pathname\here'",
	'39':"VariantPath Traversal: 'C:dirname'",
	'40':"VariantPath Traversal: '\\UNC\share\name\' ",
	'386':'BaseSymbolic Name not Mapping to Correct Object',
	'41':'BaseImproper Resolution of Path Equivalence',
	'42':"VariantPath Equivalence: 'filename.' ",
	'43':"VariantPath Equivalence: 'filename....' ",
	'44':"VariantPath Equivalence: 'file.name' ",
	'45':"VariantPath Equivalence: 'file...name' ",
	'46':"VariantPath Equivalence: 'filename ' ",
	'47':"VariantPath Equivalence: ' filename' ",
	'48':"VariantPath Equivalence: 'file name' ",
	'49':"VariantPath Equivalence: 'filename/' ",
	'50':"VariantPath Equivalence: '//multiple/leading/slash'",
	'51':"VariantPath Equivalence: '/multiple//internal/slash'",
	'52':"VariantPath Equivalence: '/multiple/trailing/slash//'",
	'53':"VariantPath Equivalence: '\multiple\\internal\backslash'",
	'54':"VariantPath Equivalence: 'filedir\' ",
	'55':"VariantPath Equivalence: '/./' ",
	'56':"VariantPath Equivalence: 'filedir' ",
	'57':"VariantPath Equivalence: 'fakedir/../realdir/filename'",
	'58':'VariantPath Equivalence: Windows 8.3 Filename',
	'59':'BaseImproper Link Resolution Before File Access ',
	'61':'CompositeUNIX Symbolic Link ',
	'62':'VariantUNIX Hard Link',
	'64':'VariantWindows Shortcut Following ',
	'65':'VariantWindows Hard Link',
	'66':'BaseImproper Handling of File Names that Identify Virtual Resources',
	'67':'VariantImproper Handling of Windows Device Names',
	'69':'VariantImproper Handling of Windows ::DATA Alternate Data Stream',
	'72':'VariantImproper Handling of Apple HFS+ Alternate Data Stream Path',
	'827':'VariantImproper Control of Document Type Definition',
	'98':'VariantImproper Control of Filename for Include/Require Statement in PHP Program ',
	'749':'BaseExposed Dangerous Method or Function',
	'618':'BaseExposed Unsafe ActiveX Method',
	'782':'VariantExposed IOCTL with Insufficient Access Control',
	'911':'BaseImproper Update of Reference Count',
	'913':'ClassImproper Control of Dynamically-Managed Code Resources',
	'470':'BaseUse of Externally-Controlled Input to Select Classes or Code ',
	'502':'BaseDeserialization of Untrusted Data',
	'914':'BaseImproper Control of Dynamically-Identified Variables',
	'621':'BaseVariable Extraction Error',
	'627':'BaseDynamic Variable Evaluation',
	'915':'BaseImproperly Controlled Modification of Dynamically-Determined Object Attributes',
	'94':'BaseImproper Control of Generation of Code ',
	'95':'VariantImproper Neutralization of Directives in Dynamically Evaluated Code ',
	'96':'BaseImproper Neutralization of Directives in Statically Saved Code ',
	'97':'VariantImproper Neutralization of Server-Side Includes ',
	'922':'ClassInsecure Storage of Sensitive Information',
	'312':'BaseCleartext Storage of Sensitive Information',
	'313':'VariantCleartext Storage in a File or on Disk',
	'314':'VariantCleartext Storage in the Registry',
	'315':'VariantCleartext Storage of Sensitive Information in a Cookie',
	'316':'VariantCleartext Storage of Sensitive Information in Memory',
	'317':'VariantCleartext Storage of Sensitive Information in GUI',
	'318':'VariantCleartext Storage of Sensitive Information in Executable',
	'921':'BaseStorage of Sensitive Data in a Mechanism without Access Control',
    '20':'Improper Input Validation',
    '79':'Failure to Preserve Web Page Structure ("Cross-site Scripting")',
    '264':'Permissions, Privileges, and Access Controls',
    '254':'7PK - Security Features',
    '19':'Data Processing Errors',
    '190':'Integer Overflow or Wraparound',
    '367':'Time-of-check Time-of-use (TOCTOU) Race Condition',
    '331':'Insufficient Entropy',
    '362':"Concurrent Execution using Shared Resource with Improper Synchronization ('Race Condition')",
    '755':'Improper Handling of Exceptional Conditions',
    '131':'Incorrect Calculation of Buffer Size',
    '476':'NULL Pointer Dereference',
    '399':'Resource Management Errors',
    '255':'Credentials Management Errors',
    '310':'Cryptographic Issues',
    '129':'Improper Validation of Array Index',
    '77': 'Improper Neutralization of Special Elements used in a Command ("Command Injection")',
    '347': 'Improper Verification of Cryptographic Signature',
    '327': 'Use of a Broken or Risky Cryptographic Algorithm',
    '345': 'Insufficient Verification of Data Authenticity',
    '354': 'Improper Validation of Integrity Check Value',
}